---
title: "Figure 9 - Agreement for sign of mid-Holocene Hydroclimate Anomalies - Scatter"
author: "Chris Hancock"
output: github_document
---

#### Load Packages

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(cowplot)
library(egg)
library(geoChronR)
library(ggrepel)
library(ggplot2)
library(ggstar)
library(lipdR)
library(maptools)
library(proj4)
library(RColorBrewer)
library(rworldmap)
library(scales)
library(sp)
library(tidyverse)

print("Packages Loaded")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#Set Working Directory

wd = '/Volumes/GoogleDrive/My Drive/zResearch/Manuscript/2021_HoloceneHydroclimate/2021_HoloceneHydroclimate/'
#knitr::opts_knit$set(root.dir = wd)
```

#### Load Data

```{r echo=TRUE, message=FALSE, warning=FALSE}
var     <- 'HC'
lipdTSO <- readRDS(file.path(wd,'Data','Proxy','lipdData.rds'))[[var]]
proxyDf <- read.csv(file=file.path(wd,'Data','Proxy',paste0('proxyMetaData_',var,'.csv')))
print("Proxy data loaded ")

#Load IPCC region data
load(url('https://github.com/SantanderMetGroup/ATLAS/blob/main/reference-regions/IPCC-WGI-reference-regions-v4_R.rda?raw=true'), verbose = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#Set Projections
PROJ     <- '+proj=robin   +ellps=WGS84 +datum=WGS84 +no_defs +lon_0=0 +x_0=0 +y_0=0 +units=m'
PROJorig <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
#Transform projection
refregions <-  spTransform(IPCC_WGI_reference_regions_v4, CRSobj = PROJ)
#Countries for basemap
countries  <- rworldmap::getMap("less islands")
countries  <- sp::spTransform(countries,  CRSobj = PROJ)
#Transform proxy projections
pointData  <- data.frame(longitude=c(proxyDf$longitude),latitude=c(proxyDf$latitude))
pointData  <- SpatialPointsDataFrame(coords=pointData, data=pointData, 
                                     proj4string=CRS(PROJorig))
pointData  <- spTransform(pointData,CRSobj = PROJ)
proxyDf$lonsPrj <- pointData@coords[,1]
proxyDf$latsPrj <- pointData@coords[,2]
```

#### Figure Settings

```{r echo=TRUE, message=FALSE, warning=FALSE}
save     <- TRUE
specific <- TRUE 

if (save){ print(paste0("save ",var," figs"))
} else{    print(paste0("plot ",var," figs"))}

figFont <- 'Times New Roman'
figText <- 10
figSize <- c(6.5,3)
```

#### Load Model Data
```{r}
var <- 'pre'

modelTSpath <- file.path(wd,'Data','Model','RegionalTS')

#Load Data
proxyDataAgree    <- read.csv(file.path(wd,'Data','Proxy','proxyMetaData_HC.csv'))
proxyRegionTS     <- read.csv(file.path(wd,'Data','RegionComposites','HC','MedianTS_byRegion.csv'))
hadcmRegionTS_ann <- read.csv(file.path(modelTSpath,paste('regional_',var,'_ANN_hadcm_land.csv',sep='')))
traceRegionTS_ann <- read.csv(file.path(modelTSpath,paste('regional_',var,'_ANN_trace_land.csv',sep='')))
hadcmRegionTS_jja <- read.csv(file.path(modelTSpath,paste('regional_',var,'_JJA_hadcm_land.csv',sep='')))
traceRegionTS_jja <- read.csv(file.path(modelTSpath,paste('regional_',var,'_JJA_trace_land.csv',sep='')))
hadcmRegionTS_djf <- read.csv(file.path(modelTSpath,paste('regional_',var,'_DJF_hadcm_land.csv',sep='')))
traceRegionTS_djf <- read.csv(file.path(modelTSpath,paste('regional_',var,'_DJF_trace_land.csv',sep='')))

cmipRegionTS_ann <- read.csv(file.path(modelTSpath,paste('regional_',var,'_ANN_cmip6_land.csv',sep='')))

```



```{r echo=FALSE, message=FALSE, warning=FALSE}

#Colors and Shapes

plotSettings <- vector(mode='list')
Csettings <- c("#92C5DE","#4393C3",'#2166AC')
if (var == 'HC'){
  if(specific){
    plotSettings$names <- sort(unique(proxyDf$CategorySpec))
    #https://carto.com/carto-colors/
    plotSettings$color <- as.character(plotSettings$names)
    plotSettings$color[which(plotSettings$names=="Glacier Ice (Accumulation)")] <- "#5F4690" #"powder blue"
    plotSettings$color[which(plotSettings$names=="Shoreline (Lake Level)")]  <- "#38A6A5" #"corn flower blue"
    plotSettings$color[which(plotSettings$names=="Lake Sediment (δ18O)")]    <- "#1D6996" #"dark blue"
    plotSettings$color[which(plotSettings$names=="Leaf Wax (δD)")]           <- "#94346E" # "dark orchid" #δ
    plotSettings$color[which(plotSettings$names=="Other (calibrated)")]      <- "grey40" #"grey40"
    plotSettings$color[which(plotSettings$names=="Other (not calibrated)")]  <- "grey" #"grey"
    plotSettings$color[which(plotSettings$names=="Pollen (calibrated)")]     <- "#0F8554" #"forest green"
    plotSettings$color[which(plotSettings$names=="Pollen (not calibrated)")] <- "#73AF48" #"" #"yellowgreen"
    plotSettings$color[which(plotSettings$names=="Speleothem (other)")]      <- "#EDAD08" #"darkorange"
    plotSettings$color[which(plotSettings$names=="Speleothem (δ13C)")]       <- "#E17C05" #"lightcoral"
    plotSettings$color[which(plotSettings$names=="Speleothem (δ18O)")]       <- "#CC503E" #"firebrick"
    #
    plotSettings$shape <- as.character(plotSettings$names) 
    plotSettings$shape[which(plotSettings$names=="Glacier Ice (Accumulation)")] <- 12
    plotSettings$shape[which(plotSettings$names=="Shoreline (Lake Level)")]  <- 21
    plotSettings$shape[which(plotSettings$names=="Lake Sediment (δ18O)")]    <- 15
    plotSettings$shape[which(plotSettings$names=="Leaf Wax (δD)")]           <- 5
    plotSettings$shape[which(plotSettings$names=="Other (calibrated)")]      <- 6
    plotSettings$shape[which(plotSettings$names=="Other (not calibrated)")]  <- 13
    plotSettings$shape[which(plotSettings$names=="Pollen (calibrated)")]     <- 14
    plotSettings$shape[which(plotSettings$names=="Pollen (not calibrated)")] <- 1
    plotSettings$shape[which(plotSettings$names=="Speleothem (other)")]      <- 17
    plotSettings$shape[which(plotSettings$names=="Speleothem (δ13C)")]       <- 23
    plotSettings$shape[which(plotSettings$names=="Speleothem (δ18O)")]       <- 11  
  } else{
    plotSettings$names <- sort(unique(proxyDf$Category))
    #
    plotSettings$color <- as.character(plotSettings$names)
    plotSettings$color[which(plotSettings$names=="Glacier Ice")]             <- "powder blue"
    plotSettings$color[which(plotSettings$names=="Shoreline")]               <- "corn flower blue"
    plotSettings$color[which(plotSettings$names=="Lake Sediment (δ18O)")]    <- "dark blue"
    plotSettings$color[which(plotSettings$names=="Leaf Wax (δD)")]           <- "dark orchid"
    plotSettings$color[which(plotSettings$names=="Other")]                   <- "grey"
    plotSettings$color[which(plotSettings$names=="Pollen")]                  <- "forest green"
    plotSettings$color[which(plotSettings$names=="Speleothem")]              <- "firebrick"
    #
    plotSettings$shape <- as.character(plotSettings$names) 
    plotSettings$shape[which(plotSettings$names=="Glacier Ice")]             <- 12
    plotSettings$shape[which(plotSettings$names=="Shoreline")]               <- 21
    plotSettings$shape[which(plotSettings$names=="Lake Sediment (δ18O)")]    <- 15
    plotSettings$shape[which(plotSettings$names=="Leaf Wax (δD)")]           <- 5
    plotSettings$shape[which(plotSettings$names=="Other")]                   <- 13
    plotSettings$shape[which(plotSettings$names=="Pollen")]                  <- 14
    plotSettings$shape[which(plotSettings$names=="Speleothem")]              <- 11
  }
} else if (var == 'T'){
  plotSettings$names <- sort(unique(proxyDf$Category))
  #
  plotSettings$color <- as.character(plotSettings$names)
  plotSettings$color[which(plotSettings$names=="alkenone")]          <- "tomato"
  plotSettings$color[which(plotSettings$names=="biophysical")]       <- "skyblue4"
  plotSettings$color[which(plotSettings$names=="chironomid")]        <- "firebrick"
  plotSettings$color[which(plotSettings$names=="isotope")]           <- "orange"
  plotSettings$color[which(plotSettings$names=="Mg/Ca")]             <- "midnight blue"
  plotSettings$color[which(plotSettings$names=="other biomarker")]   <- "medium blue"
  plotSettings$color[which(plotSettings$names=="other ice")]         <- "powder blue"
  plotSettings$color[which(plotSettings$names=="other microfossil")] <- "plum4"
  plotSettings$color[which(plotSettings$names=="pollen")]            <- "forest green"
  #
  plotSettings$color[which(plotSettings$names=="alkenone")]          <- 22 
  plotSettings$color[which(plotSettings$names=="biophysical")]       <- 1 
  plotSettings$color[which(plotSettings$names=="chironomid")]        <- 30 
  plotSettings$color[which(plotSettings$names=="isotope")]           <- 15 
  plotSettings$color[which(plotSettings$names=="Mg/Ca")]             <- 25 
  plotSettings$color[which(plotSettings$names=="other biomarker")]   <- 13 
  plotSettings$color[which(plotSettings$names=="other ice")]         <- 12
  plotSettings$color[which(plotSettings$names=="other microfossil")] <- 5 
  plotSettings$color[which(plotSettings$names=="pollen")]            <- 14 
}
plotSettings$shape <- as.numeric(plotSettings$shape)


monsoonC<- '#ED645A'
tropicC <- '#DAA51B'
sml     <- '#24796C'
nml     <- '#2F8AC4'
polar   <- '#A5AA99'
```


#### Calculate values
```{r echo=FALSE, message=FALSE, warning=FALSE}
#Create Empty DF
regNames <-  names(proxyRegionTS[-1])
NAs <- rep(NA,length(regNames))
data <- data.frame(regions=regNames,
                   regType=NAs,
                   proxyAgreePct=NAs,
                   #proxyhadcmCor=NAs,
                   #proxytraceCor=NAs,
                   #hadcmVariance=NAs,
                   #traceVariance=NAs,
                   hadcmRange=NAs,
                   traceRange=NAs,
                   averageRange=NAs,
                   hadcmSummerPct=NAs,
                   traceSummerPct=NAs,
                   averageSummerPct=NAs)

#Populate DF
for (reg in regNames){
  row <- which(regNames==reg)
  #
  proxySub  <- proxyDataAgree[which(proxyDataAgree$ipccReg == reg),]
  proxyVals <- proxySub$ka_6-proxySub$ka_0.5
  for (i in (which(proxySub$direction=='negative'))){proxyVals[i] <- proxyVals[i]*-1}
  proxyVals <- proxyVals[which(!is.na(proxyVals))]
  proxyVals <- proxyVals[which(proxyVals != 0)]
  data[row,'regions'] <- reg
  data[row,'proxyAgreePct'] <- abs(round(100*length(which(proxyVals>0))/length(proxyVals),1)-50)+50
  if (reg %in% c('EAS','TIB','SAS','NEAF','SAH','ESAF','SAM')){data[row,'regType'] <- 'Tropics (Monsoon)'
  } else if (reg %in% c('NCA','SCA','NES','SEAF','SEA','WSAF','NWS')){      data[row,'regType'] <- 'Tropics (Non-Monsoon)'
  } else if (reg %in% c('SAU','NZ','SSA')){                   data[row,'regType'] <- 'Midlatitude (Southern)'
  } else if (reg %in% c('NEN','NWN','ENA','CNA','WNA','NEU','WCE','MED','EEU','WCA','ECA','WSB','ESB','RFE')){data[row,'regType'] <- 'Midlatitude (Northern)'
  }else{data[row,'regType'] <-'Polar'}
  data[row,'cmip6Range'] <- mean(cmipRegionTS_ann[,reg])
  data[row,'hadcmRange'] <- -1*(mean(hadcmRegionTS_ann[which(between(hadcmRegionTS_ann$X,0,1000)),reg],na.rm=TRUE)-mean(hadcmRegionTS_ann[which(between(hadcmRegionTS_ann$X,5500,6500)),reg],na.rm=TRUE)) #diff(range(hadcmRegionTS_ann[,reg],na.rm=TRUE))
  data[row,'traceRange'] <- -1*(mean(traceRegionTS_ann[which(between(traceRegionTS_ann$X,0,1000)),reg],na.rm=TRUE)-mean(traceRegionTS_ann[which(between(traceRegionTS_ann$X,5500,6500)),reg],na.rm=TRUE))#diff(range(traceRegionTS_ann[,reg],na.rm=TRUE))
  data[row,'proxyAgreePct'] <- (round(100*length(which(proxyVals>0))/length(proxyVals),1)-50)*sign(mean(data[row,'hadcmRange'],data[row,'traceRange']))+50
  #data[row,'proxyAgreePct'] <- (round(100*length(which(proxyVals>0))/length(proxyVals),1)-50)*sign(median(data[row,'cmip6Range']))+50
  #Nick/Michael comments
  data[row,'hadcmRange'] <- abs(data[row,'hadcmRange'])
  data[row,'traceRange'] <- abs(data[row,'traceRange'])
  #data[row,'hadcmRange'] <- 100*data[row,'hadcmRange']/mean(mean(hadcmRegionTS_ann[which(between(hadcmRegionTS_ann$X,0,1000)),reg],na.rm=TRUE),mean(hadcmRegionTS_ann[which(between(hadcmRegionTS_ann$X,5500,6500)),reg],na.rm=TRUE)) #diff(range(hadcmRegionTS_ann[,reg],na.rm=TRUE))
  #data[row,'traceRange'] <- 100*data[row,'traceRange']/mean(mean(traceRegionTS_ann[which(between(traceRegionTS_ann$X,0,1000)),reg],na.rm=TRUE),mean(traceRegionTS_ann[which(between(traceRegionTS_ann$X,5500,6500)),reg],na.rm=TRUE)) #diff(range(traceRegionTS_ann[,reg],na.rm=TRUE))
  data[row,'averageRange'] <- mean(c(data[row,'traceRange'],data[row,'hadcmRange']))
  if (reg %in% c('NWS','SAM','NES','SSA','WSAF','ESAF','SAU','NZ','EAF')){
    data[row,'hadcmSummerPct']<-round(100*mean(traceRegionTS_djf[,reg],na.rm=TRUE)/(mean(traceRegionTS_ann[,reg],na.rm=TRUE)*4))
    data[row,'traceSummerPct']<-round(100*mean(hadcmRegionTS_djf[,reg],na.rm=TRUE)/(mean(hadcmRegionTS_ann[,reg],na.rm=TRUE)*4))
  } else{
    data[row,'hadcmSummerPct']<-round(100*mean(traceRegionTS_jja[,reg],na.rm=TRUE)/(mean(traceRegionTS_ann[,reg],na.rm=TRUE)*4))
    data[row,'traceSummerPct']<-round(100*mean(hadcmRegionTS_jja[,reg],na.rm=TRUE)/(mean(hadcmRegionTS_ann[,reg],na.rm=TRUE)*4))
  }
  data[row,'averageSummerPct'] <- mean(c(data[row,'hadcmSummerPct'],data[row,'traceSummerPct']))
}

pointData <- data.frame(longitude=c(proxyDf$longitude),latitude=c(proxyDf$latitude))
pointData <- spTransform(SpatialPointsDataFrame(coords=pointData,data = pointData, proj4string = CRS(PROJorig)),CRSobj = PROJ)
proxyDf$lonsPrj <- pointData@coords[,1]
proxyDf$latsPrj <- pointData@coords[,2]

dataTable <- fortify(subset(refregions, Acronym %in% names(proxyRegionTS)))
dataTable$regType     <- NA
dataTable$regType[which(dataTable$id %in% c('NEN','NWN','ENA','CNA','WNA','NEU','WCE','MED','EEU','WCA','ECA','WSB','ESB','RFE'))] <- '#1D6996'
dataTable$regType[which(dataTable$id %in% c('SAU','NZ','SSA'))] <- '#0F8554'
dataTable$regType[which(dataTable$id %in% c('GIC','EAN'))] <- '#6F4070'
dataTable$regType[which(dataTable$id %in% c('EAS','TIB','SAS','NEAF','SAH','ESAF','SAM'))] <- '#CC503E'
dataTable$regType[which(dataTable$id %in% c('NCA','SCA','NES','SEAF','SEA','WSAF','NWS'))] <- '#EDAD08'
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
IPCC <- TRUE
basemap <- ggplot() +
  borders(aggregate(refregions, FUN=length), fill=NA, color='black', size=2) +
  geom_map(data=refregions, map=fortify(refregions), 
           aes(x=long, y=lat, group=group, map_id=id), fill="white", color="white", size=1)+
  geom_map(data=countries,  map=fortify(countries),  
           aes(x=long, y=lat, group=group, map_id=id), fill ="grey80",color="grey90",size=0.2) +
  coord_fixed(1) + 
  theme_void() 

proxyMapRegions <- basemap + 
  #Add refrence regions boundaries
  geom_map(data=subset(refregions, Acronym %in% names(proxyRegionTS)), 
           map=dataTable, alpha=0.6, size=0.1, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id,fill=as.factor(dataTable$regType))) +
  scale_fill_manual(values=c(sml,nml,polar,monsoonC,tropicC))+
  #Add proxy sites
  geom_point(data=as.data.frame(proxyDf), aes(x=lonsPrj , y=latsPrj), shape=1,size=0.5,stroke=0.3) +
  #Format Legend
  theme(plot.background = element_rect(fill = NA,color=NA),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.position = 'none')

proxyMapRegions


```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plyr )
df <- na.omit(data)
find_hull <- function(df) df[chull(df$proxyAgreePct, df$averageRange), ]
hulls <- ddply(df, "regType", find_hull)

scatter <- ggplot(data=data,aes(x=averageRange,y=proxyAgreePct,shape=regType,fill=regType,group = regType))+
  geom_hline(yintercept = 50,size=0.2)+
  geom_polygon(data = hulls, alpha = 0.6) +
  geom_point(size=2.5,color='Black')+
  geom_point(size=2.5,color='Black')+
  annotate("text",label="50% Proxy \n Even Wet/Dry Split",                        
           x = 0.21, y = 50,family=figFont,color='grey40',size=3)+
  annotate("text",label="Proxy-Proxy Agreement & \n Proxy-Model Agreement",      
           x = 0.21, y = 90,family=figFont,color='grey40',size=3)+
  annotate("text",label="Proxy-Proxy Agreement but \n Proxy-Model Disagreement", 
           x = 0.21, y = 10,family=figFont,color='grey40',size=3)+
  annotate("segment", x = 0.21, xend = 0.21, y = 60, yend = 80, colour = "grey40", size=0.7, arrow=arrow(type='closed',length = unit(0.05, "inches")))+
  annotate("segment", x = 0.21, xend = 0.21, y = 40, yend = 20, colour = "grey40", size=0.7, arrow=arrow(type='closed',length = unit(0.05, "inches")))+
  scale_fill_manual(values=c(nml,sml,polar,monsoonC,tropicC))+
  scale_shape_manual(values=c(24,25,23,21,22))+
  theme_bw()+
  #scale_x_continuous(limits=c(0,1000))+
  coord_cartesian(xlim=c(0,0.28), ylim=c(0,100),expand	=FALSE) +
  labs(y='Proxy Agreement with Sign of Mid-Holocene Anomaly \n (% of proxy records within each region) ',
       #% of Proxy Records with the Same Sign 6-0 ka Anomaly \n as the Simulated 6-0 ka Anomaly',
       x='Magnitude of Simulated Mid-Holocene Anomaly \n (absolute value of mm/day)')+
  #labs(y='% of Proxy Records With the Same Sign 6-0 ka Anomaly',x='Absolute Value of Simulated 6-0 ka Anomalies \n _______________________________________ \n \n Mean of Values At 0ka and 6ka')+
  theme(legend.position = 'bottom',
        legend.title = element_blank(),
        text = element_text(family=figFont,size=9),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        panel.grid.minor.x=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.grid.minor.y=element_blank(),
        plot.background= element_blank(),
        legend.key.height=unit(0.15,"in"),
        legend.key.width=unit( 0.15,"in"),
        legend.background	= element_rect(fill='white',color='white'))+    
  
  guides(fill = guide_legend(ncol = 1))
scatter


```


```{r echo=TRUE, message=FALSE, warning=FALSE}
plt <- cowplot::ggdraw(ggplot() + 
                       coord_cartesian(xlim=c(0,1),ylim=c(0,1),expand=FALSE)+
                       annotate("text",label="(a)", x = 0.05, y = 0.9,family=figFont,color='black',size=4)+
                       annotate("text",label="(b)", x = 0.35, y = 0.9,family=figFont,color='black',size=4)+

                       theme_void()+
                       theme(plot.background= element_rect(colour='White',fill='White'),
                             panel.background = element_rect(colour='White',fill='White')))+
    draw_plot(ggpubr::as_ggplot(get_legend(scatter)),       x = 0,     y = 0, width = 0.4, height = 0.5)+
    draw_plot(scatter+theme(legend.position='None'),        x = 0.4,   y = 0, width = 0.6, height = 1)+
                        #annotate("text",label="EAS", x = 0.52, y = 0.85,family=figFont,color=monsoonC,size=3)+
                        #annotate("text",label="NWS", x = 0.68, y = 0.26,family=figFont,color=tropicC,size=3)+
                        #annotate("text",label="ESB", x = 0.54, y = 0.26,family=figFont,color=nml,size=3)+

  draw_plot(proxyMapRegions,  x = 0,   y = 0.25, width = 0.4, height = 0.7)


monsoonC<- '#ED645A'
tropicC <- '#DAA51B'
sml     <- '#24796C'
nml     <- '#2F8AC4'
polar   <- '#A5AA99'
  
plt
```



```{r}

if (save) {
  ggsave(plot=plt, width = 6.5, height = 3.25, dpi = 600,
         filename = file.path(wd,"Figures","Model",'ProxyAgreeByModelAnom.png'))
}
```




