---
goal: Create r.data files for temp12k and hc12k to refrence from. 
      Also assign regional designations and additional metadata. 
input: LiPD files; refRegions
output: rdata for Temp12k and HC12k ts
author: chris hancock
---

###Settings in script
```{r}
#Set up directories and names
dataDir   <- '/Volumes/GoogleDrive/My Drive/zResearch/Data/'
githubDir <- '/Volumes/GoogleDrive/My Drive/zResearch/HoloceneHydroclimate/'
dataDir   <- 'G:/My Drive/zResearch/Data/'
githubDir <- 'G:/My Drive/zResearch/HoloceneHydroclimate/'
setwd(githubDir)
#Which versions of datesets to use
tempVers <- '1_0_2'
hcVers   <- '0_1_0'
#Cut off for lake deposite numbers
lakeDeposNo <- 9
#
```


###Load Packages
```{r}
library(lipdR)
library(maptools)
library(proj4)
library(sf)
library(sp)
library(tidyverse)
```


###Load ipcc region spatial data
```{r}
PROJ <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
refregions <- readShapePoly(paste(githubDir,                      'DataFiles/IPCC-WGI-reference-regions-v4_shapefile/IPCC-WGI-reference-regions-v4.shp',
                              sep=''),
                            
                            proj4string=CRS("+proj=longlat +ellps=WGS84"))
refregions <-  spTransform(refregions, CRSobj = PROJ)
```


###Load LiPD Data #NEED TO REVISE
```{r}
#Load Lipd Files
Dall <- readLipd(paste(dataDir,'LiPD/database',sep=''))
Dnew <- readLipd(paste(dataDir,'LiPD/NewHoloceneHydroclimate',sep=''))

#Combine LiPD files and extract data from 2 sources without duplicates
TS    <- extractTs(Dnew)
TSall <- extractTs(Dall)

#Don't include duplicates
dataSetNameList <- pullTsVariable(TS,"dataSetName")
dataSetNameList <- c(dataSetNameList,
                     'Pass Age Control','Dune.Finney.2012','Dunee.Finney.2012')
for (ts in 1:length(TSall)){
  if (TSall[[ts]]$dataSetName %in% dataSetNameList == FALSE){
    TS <- append(TS,TSall[ts])
  }
}
TS <- splitInterpretationByScope(TS)

```



###Assign tsids for data compilations based on within correct dataset and version 
```{r}
tsidListHC   <- c()
tsidListTemp <- c()
for (ts in TS){
  compNo <- 1
  while (!is.null(ts[[paste('inCompilationBeta',compNo,'_compilationName',sep='')]])){
    compName <- ts[[paste('inCompilationBeta',compNo,'_compilationName',sep='')]]
    compVers <- ts[[paste('inCompilationBeta',compNo,'_compilationVersion',sep='')]]
    if (compName == 'Temp12k'){
      if (any(compVers == tempVers)){
        tsidListTemp <- c(tsidListTemp,ts$paleoData_TSid)
      }
    } else if (compName == 'HoloceneHydroclimate'){
      if (any(compVers == hcVers)){
        if (sum(!is.na(ts$paleoData_values[which(ts$age < 12000)])) >= lakeDeposNo){
          tsidListHC <- c(tsidListHC,ts$paleoData_TSid)
        }
      }
    }
    compNo <- compNo+1
  }
}

print(paste("Temp:",length(tsidListTemp)))
print(paste("HC:",length(tsidListHC)))

lipdData <- list(Temp = TS[which(pullTsVariable(TS,"paleoData_TSid") %in% tsidListTemp)], 
                 HC = TS[which(pullTsVariable(TS,"paleoData_TSid") %in% tsidListHC)])
```


###Add metadata
```{r}
for (climVar in names(lipdData)){
  lipd <- lipdData[[climVar]]
  for (ts in 1:length(lipd)){
    #Make sure name of climate interp field is standardized 
    if (is.null(lipd[[ts]]$climateInterpretation1_direction) == FALSE){
      lipd[[ts]]$climateInterpretation1_interpDirection <- lipd[[ts]]$climateInterpretation1_direction
    }
    #
    #Add Ipcc regions to metdata
    pointData <- data.frame(longitude=c(lipd[[ts]]$geo_longitude),latitude=c(lipd[[ts]]$geo_latitude))
    pointData <- SpatialPointsDataFrame(coords=pointData,data = pointData, 
                                        proj4string = CRS("+proj=longlat +ellps=WGS84"))
    pointData <-  spTransform(pointData, CRSobj = PROJ)
    lipd[[ts]]$geo_ipccRegion <- as.character(over(pointData, refregions)$Acronym)
    #
    #Add age information
    tso <- data_frame(age = lipd[[ts]]$age, values = lipd[[ts]]$paleoData_values) %>%
      filter(between(age,0,12000)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
    lipd[[ts]]$ageMin     <- min(tso$age)
    lipd[[ts]]$ageMax     <- max(tso$age)
    lipd[[ts]]$ageRange   <- diff(range(tso$age))
    lipd[[ts]]$ageRes     <- median(diff(tso$age))
    lipd[[ts]]$ageResPlus <- median(diff(tso$age[which(diff(tso$values) != 0)]))
    #
    #Add category information
    if (climVar == 'HC'){
      archive  <- lipd[[ts]]$archiveType
      proxy    <- lipd[[ts]]$paleoData_proxy
      unit     <- lipd[[ts]]$paleoData_units
      if (is.null(proxy) | is.null(archive)){
        lipd[[ts]]$Category         <- 'Other'
        lipd[[ts]]$CategorySpecific <- 'Other (not calibrated)'
      } else if (archive == 'Speleothem'){
        lipd[[ts]]$Category           <- 'Speleothem'
        if (proxy == 'd18O' | proxy ==  'd13C'){
          lipd[[ts]]$CategorySpecific <- paste(archive,' (',proxy,')',sep='')
        } else{
          lipd[[ts]]$CategorySpecific <- 'Speleothem (other)'
        }
      } else if (archive == 'LakeDeposits'){
        lipd[[ts]]$Category           <- 'Lake Deposits'
        lipd[[ts]]$CategorySpecific   <- 'Lake Deposits'
      } else if (archive == 'GlacierIce'){
        lipd[[ts]]$Category           <- 'Glacier Ice'
        lipd[[ts]]$CategorySpecific   <- 'Glacier Ice'
      } else if (archive == 'LakeSediment' & proxy == 'd18O'){
        lipd[[ts]]$Category           <- 'Lake Sediment d18O'
        lipd[[ts]]$CategorySpecific   <- 'Lake Sediment (d18O)'
      } else if (proxy == 'dDwax'){
        lipd[[ts]]$Category           <- 'Leaf Wax dD'
        lipd[[ts]]$CategorySpecific   <- 'Leaf Wax (dD)'
      } else if (proxy == 'pollen'){
        lipd[[ts]]$Category           <- 'Pollen'
        if (is.null(unit)){
          lipd[[ts]]$CategorySpecific <- 'Pollen (not calibrated)'
        } else if (unit == 'mm' | unit == 'mm/a'){
          lipd[[ts]]$CategorySpecific <- 'Pollen (calibrated)'
        } else {
          lipd[[ts]]$CategorySpecific <- 'Pollen (not calibrated)'
        }
      } else {
        lipd[[ts]]$Category           <- 'Other'
        if (is.null(unit)){
          lipd[[ts]]$CategorySpecific <- 'Other (not calibrated)'
        } else if (unit == 'mm' | unit == 'mm/a'){
          lipd[[ts]]$CategorySpecific <- 'Other (calibrated)'
        } else {
          lipd[[ts]]$CategorySpecific <- 'Other (not calibrated)'
        }
      }
    }
    #
  }
  #require >0 change points for lakedeposits
  lipdData[[climVar]] <- lipd[which(!is.na(pullTsVariable(lipd,"ageResPlus")))] 
}
```


###Save
```{r}
saveRDS(lipdData, "lipdData.rds")
```
