---
title: "Untitled"
author: "Chris Hancock"
date: "6/2/2022"
output: html_document
---
###Load packages 
```{r warning=FALSE}
library(cowplot)
library(egg)
library(geoChronR)
library(ggrepel)
library(ggplot2)
library(ggstar)
library(lipdR)
library(maptools)
library(proj4)
library(RColorBrewer)
library(rworldmap)
library(scales)
library(sp)
library(tidyverse)
dir <- "/Users/chrishancock/Dropbox"
dir <- "C://Users/clh624/Dropbox/"

```

```{r}
D_hc <- readLipd(paste('http://lipdverse.org/HoloceneHydroclimate/','0_4_0','/HoloceneHydroclimate','0_4_0','.zip',sep=''))
TS_Lake <- splitInterpretationByScope(extractTs(D_hc))
TS_Lake <- TS_Lake[which(pullTsVariable(TS_Lake,'createdBy')=="http://github.com/nickmckay/oxfordLakeStatus2Lipd")]
TS_Lake <- TS_Lake[pullTsVariable(TS_Lake,'paleoData_variableName')=='lakeStatus']
```

```{r}
lipd <- TS_Lake
TSids <- c()
for (ts in 1:length(lipd)){
    #Add age information
    tso <- data.frame(age = as.numeric(lipd[[ts]]$age), values = as.numeric(lipd[[ts]]$paleoData_values)) %>%
      filter(between(age,-100,12400)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
    if (nrow(tso) >= 11){
      #if (length(unique(tso$values)) >= 2){
      if (length(which(diff(tso$values) != 0)) >= 2){
       TSids <- append(TSids,lipd[[ts]]$paleoData_TSid) 
      }
    }
}
print(length(TSids))
View(as.data.frame(TSids))
```

###Input Data
```{r, warning=FALSE}
Dlake   <- readLipd(file.path(dir,"PaleoDIVER"))
```
```{r}
TS_Lake <- splitInterpretationByScope(extractTs(Dlake))
TS_Lake <- TS_Lake[which(pullTsVariable(TS_Lake,'paleoData_TSid')=='pdR0NFxIRcqx0L6n7X5')]
print(length(TS_Lake))
ts <- 1
tso <- data.frame(age = as.numeric(lipd[[ts]]$age), values = as.numeric(lipd[[ts]]$paleoData_values)) %>%
      filter(between(age,-100,12400)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
print(tso)
```

```{r}
TS_Lake <- splitInterpretationByScope(extractTs(Dlake))
TS_Lake <- TS_Lake[which(pullTsVariable(TS_Lake,'paleoData_primaryTimeseries')==TRUE)]
lipd <- TS_Lake
TSids <- c()
for (ts in 1:length(lipd)){
    #Add age information
    include <- FALSE
    tso <- data.frame(age = as.numeric(lipd[[ts]]$age), values = as.numeric(lipd[[ts]]$paleoData_values)) %>%
      filter(between(age,-100,12000)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
    if (nrow(tso) < 10) {next}
    lipd[[ts]]$ageMin     <- min(tso$age)
    lipd[[ts]]$ageMax     <- max(tso$age)
    lipd[[ts]]$ageRange   <- diff(range(tso$age))
    lipd[[ts]]$ageRes     <- median(diff(tso$age))
    lipd[[ts]]$ageResPlus <- median(diff(tso$age[which(diff(tso$values) != 0)]))
    if (!is.na(lipd[[ts]]$ageRange)){
      if (lipd[[ts]]$ageRange > 6000 & lipd[[ts]]$ageRes < 1000){
        include <- TRUE
      } else if (lipd[[ts]]$ageRange > 4000 & lipd[[ts]]$ageRes < 400){
        include <- TRUE
      }
    }
    if (include){
      TSids <- append(TSids,lipd[[ts]]$paleoData_TSid)}
}
print(length(TSids))
```


```{r}
TS_Lake <- splitInterpretationByScope(extractTs(Dlake))
TS_Lake <- TS_Lake[which(pullTsVariable(TS_Lake,'paleoData_primaryTimeseries')==TRUE)]
lipd <- TS_Lake
TSids <- c()
for (ts in 1:length(lipd)){
    #Add age information
    include <- FALSE
    tso <- data.frame(age = as.numeric(lipd[[ts]]$age), values = as.numeric(lipd[[ts]]$paleoData_values)) %>%
      filter(between(age,-100,12000)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
    if (nrow(tso) < 10) {next}
    lipd[[ts]]$ageMin     <- min(tso$age)
    lipd[[ts]]$ageMax     <- max(tso$age)
    lipd[[ts]]$ageRange   <- diff(range(tso$age))
    lipd[[ts]]$ageRes     <- median(diff(tso$age))
    lipd[[ts]]$ageResPlus <- median(diff(tso$age[which(diff(tso$values) != 0)]))
    if (!is.na(lipd[[ts]]$ageRange)){
      if (lipd[[ts]]$ageRange > 6000 & lipd[[ts]]$ageRes < 1000){
        include <- TRUE
      } else if (lipd[[ts]]$ageRange > 4000 & lipd[[ts]]$ageRes < 400){
        include <- TRUE
      }
    }
    if (include){
      TSids <- append(TSids,lipd[[ts]]$paleoData_TSid)}
}
print(length(TSids))
```

```{r}
Dpoll   <- readLipd(file.path(dir,"LegacyClimate"))
TS_Poll <- splitInterpretationByScope(extractTs(Dpoll))
TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'paleoData_primaryTimeseries')==TRUE)]
TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'climateInterpretation1_variable')=='P')]
```

```{r}
lipd <- TS_Poll
TSids <- c()
for (ts in 1:length(lipd)){
    #Add age information
    include <- FALSE
    tso <- data.frame(age = as.numeric(lipd[[ts]]$age), values = as.numeric(lipd[[ts]]$paleoData_values)) %>%
      filter(between(age,-100,12000)) %>%
      filter(!is.na(values)) %>%
      arrange(age)
    if (nrow(tso) < 10) {next}
    lipd[[ts]]$ageMin     <- min(tso$age)
    lipd[[ts]]$ageMax     <- max(tso$age)
    lipd[[ts]]$ageRange   <- diff(range(tso$age))
    lipd[[ts]]$ageRes     <- median(diff(tso$age))
    lipd[[ts]]$ageResPlus <- median(diff(tso$age[which(diff(tso$values) != 0)]))
    AgeControl <- Dpoll[[TS_Poll[[ts]]$dataSetName]]$chronData[[1]][["measurementTable"]][[1]][["age"]][["values"]]
    AgeControl <- AgeControl[which(AgeControl<=12000)]
    lipd[[ts]]$AgeControlMax <- max(diff(c(lipd[[ts]]$ageMin,AgeControl,lipd[[ts]]$ageMax)))
    lipd[[ts]]$AgeControlN   <- length(AgeControl)
    if (!is.na(lipd[[ts]]$ageRange)){
      if (lipd[[ts]]$ageRange > 4000 & lipd[[ts]]$ageRes < 400){
        if (lipd[[ts]]$AgeControlMax < 2000 & lipd[[ts]]$AgeControlN >= 2){  
          include <- TRUE
        } else if (lipd[[ts]]$AgeControlMax < 3000 & lipd[[ts]]$AgeControlN >= 3){  
          include <- TRUE
        } else if (lipd[[ts]]$AgeControlMax < 3500 & lipd[[ts]]$AgeControlN >= 5){  
          include <- TRUE
        } else if (lipd[[ts]]$AgeControlMax < 4000 & lipd[[ts]]$AgeControlN >= 6){  
          include <- TRUE
        }
      }
    } 
    if (include){
      TSids <- append(TSids,lipd[[ts]]$paleoData_TSid)}
}
print(length(TSids))
View(as.data.frame(TSids))
write.csv(as.data.frame(TSids),"/Users/clh624/Desktop/Data")
```


```{r}

dataset <- "WilliamKingFlourMill.Grant.2014"
zz <-  read.table("C://Users/clh624/Downloads/Herzschuh-etal_2021_climate-recons_Europe.tab", sep = '\t',header = TRUE)

Dpoll   <- readLipd(file.path(dir,"LegacyClimate",paste(dataset,"lpd",sep=".")))
TS_Poll <- splitInterpretationByScope(extractTs(Dpoll))
TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'paleoData_primaryTimeseries')==TRUE)]
TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'climateInterpretation1_variable')=='P')]


z <- 

recs <- pg_search(query = "doi:10.1594/PANGAEA.930512 ")

asia <-pangaear::pg_data(doi= "10.1594/PANGAEA.930606")
nams

z <-  readLines("/Users/chrishancock/Downloads/Herzschuh-etal_2021_climate-recons-model-stats_Asia.tab")
```

```{r}
dir <- "/Users/chrishancock/Dropbox"
#Dpoll   <- readLipd(file.path(dir,"LegacyClimate"))

TSids <- c()
chronData <-  read.table("/Users/chrishancock/Downloads/Table-S1_chronological_control_points_metadata.csv", sep = '\t',header = TRUE)

significance <- vector(mode='list')
significance[["Western North America"]]  <- pangaear::pg_data(doi= "10.1594/PANGAEA.930595")[[1]][["data"]]
significance[["Eastern North America"]]  <- pangaear::pg_data(doi= "10.1594/PANGAEA.930593")[[1]][["data"]]
significance[["Europe"]]                <- read.delim("/Users/chrishancock/Downloads/Herzschuh-etal_2021_climate-recons-signif_Europe.tab", sep = '\t',header = TRUE,fileEncoding="UTF-16LE")
significance[["Asia"]]                   <- pangaear::pg_data(doi= "10.1594/PANGAEA.930590")[[1]][["data"]]

colnames(significance[["Europe"]])<-names(significance[["Asia"]]  )

for (i in 1:length(Dpoll)){
  Dselect <- Dpoll[[i]]
  chronDataSelect <- chronData[which(chronData$Site_ID==Dselect$LegacyClimateSiteId & chronData$Site_Name==Dselect[["geo"]][["siteName"]]),] 
  if(is.null(Dselect[["pub"]][[1]][["citation"]])){
     chronDataSelect <- chronDataSelect[which(is.na(chronDataSelect$First_Publication)),]
  } else{
     chronDataSelect <- chronDataSelect[which(chronDataSelect$First_Publication==Dselect[["pub"]][[1]][["citation"]]),]
  }
  TS_Poll <- splitInterpretationByScope(extractTs(Dselect))
  TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'paleoData_primaryTimeseries')==TRUE)]
  TS_Poll <- TS_Poll[which(pullTsVariable(TS_Poll,'climateInterpretation1_variable')=='P')]
  for (ts in 1:length(TS_Poll)){
      #Add age information
      include <- FALSE
      tso <- data.frame(age = as.numeric(TS_Poll[[ts]]$age), values = as.numeric(TS_Poll[[ts]]$paleoData_values)) %>%
        filter(between(age,-100,12000)) %>%
        filter(!is.na(values)) %>%
        arrange(age)
      if (nrow(tso) < 10) {next}
      TS_Poll[[ts]]$ageMin     <- min(tso$age)
      TS_Poll[[ts]]$ageMax     <- max(tso$age)
      TS_Poll[[ts]]$ageRange   <- diff(range(tso$age))
      TS_Poll[[ts]]$ageRes     <- median(diff(tso$age))
      TS_Poll[[ts]]$ageResPlus <- median(diff(tso$age[which(diff(tso$values) != 0)]))
      TS_Poll[[ts]]$geo_continent
      AgeControl <- chronDataSelect[which(chronDataSelect$Dataset_ID==unique(chronDataSelect$Dataset_ID)[ts]),]$Age_Calibrated..kyr.BP*1000
      AgeControl <- AgeControl[which(AgeControl<=12000)]
      if(length(AgeControl)<=3){       thresh <- 1
      } else if(length(AgeControl)<=6){thresh <- 2
      } else{                          thresh <- length(AgeControl)*0.3334
      }
      if(length(which(diff(AgeControl)<0))>=thresh){next} #allow for 1 age reversal for every 4 age control points
      TS_Poll[[ts]]$AgeControlMax <- max(diff(c(TS_Poll[[ts]]$ageMin,AgeControl,TS_Poll[[ts]]$ageMax)))
      TS_Poll[[ts]]$AgeControlN   <- length(AgeControl)
      if (!is.na(TS_Poll[[ts]]$ageRange)){
        if (TS_Poll[[ts]]$ageRange > 4000 & TS_Poll[[ts]]$ageRes < 400){
            if (TS_Poll[[ts]]$AgeControlMax < 3000 & TS_Poll[[ts]]$AgeControlN >= 2){  
            include <- TRUE
          } else if (TS_Poll[[ts]]$AgeControlMax < 3500 & TS_Poll[[ts]]$AgeControlN >= 5){  
            include <- TRUE
          } else if (TS_Poll[[ts]]$AgeControlMax < 4000 & TS_Poll[[ts]]$AgeControlN >= 6){  
            include <- TRUE
          }
        }
      } 
      if (include){
        if (significance[[TS_Poll[[ts]]$geo_continent]][which(significance[[TS_Poll[[ts]]$geo_continent]]$`ID (Dataset)`==unique(chronDataSelect$Dataset_ID)[ts]),54]<=0.1){
          TSids <- append(TSids,TS_Poll[[ts]]$paleoData_TSid)
        }
      }
  }
  if(!is.na(unique(chronDataSelect$Dataset_ID)[ts+1])){print(Dselect$dataSetName)}
}
dir<-"/Volumes/GoogleDrive/My Drive/zResearch/Manuscript/2021_HoloceneHydroclimate/2021_HoloceneHydroclimate/Data/Proxy/LegacyClimate"
print(length(TSids))
write.csv(as.data.frame(TSids),file.path(dir,"LegacyClimateTSidPassQC.csv"))
```

```{r}  
Dselect <- Dpoll[["Bruckmisse.Rosch.2009"]]
print(Dselect$chronData[[1]][["measurementTable"]][[1]]$age$values)
for (i in 1:length(Dselect[["paleoData"]])){
  print(i)
  chronDataSelect <- chronData[which(chronData$Site_ID==Dselect$LegacyClimateSiteId & chronData$Site_Name==Dselect[["geo"]][["siteName"]]),] 
  if(is.null(Dselect[["pub"]][[1]][["citation"]])){
     chronDataSelect <- chronDataSelect[which(is.na(chronDataSelect$First_Publication)),]
  } else{
     chronDataSelect <- chronDataSelect[which(chronDataSelect$First_Publication==Dselect[["pub"]][[1]][["citation"]]),]
  }
  print(chronDataSelect[which(chronDataSelect$Dataset_ID==unique(chronDataSelect$Dataset_ID)[i]),]$Age_Calibrated..kyr.BP*1000)
}
if(!is.na(unique(chronDataSelect$Dataset_ID)[i+1])){print(Dselect$dataSetName)}

```

```{r}
figFont = 'sans'
figText = 10
#Dataset Dashboard
dataset='PaleoDiver'
lipd <- TS_Lake
colors  = c('corn flower blue', 'dark blue')
failColors = brewer.pal(3,'Dark2')[c(2,1,3)]
climVar<-'HC'
proxyDf <- tibble(dataset       = pullTsVariable(lipd,'dataSetName'),
                  tsid          = pullTsVariable(lipd,'paleoData_TSid'),
                  PassFail      = pullTsVariable(lipd,'PassFail'),
                  longitude     = pullTsVariable(lipd,'geo_longitude'),
                  latitude      = pullTsVariable(lipd,'geo_latitude'),
                  ipccReg       = pullTsVariable(lipd,'geo_ipccRegion'),
                  archive       = pullTsVariable(lipd,'archiveType'),
                  #proxy         = pullTsVariable(lipd,'paleoData_proxy'),
                  minAge        = pullTsVariable(lipd,'ageMin'),
                  maxAge        = pullTsVariable(lipd,'ageMax'),
                  recordRange   = pullTsVariable(lipd,'ageRange'),
                  recordRes     = pullTsVariable(lipd,'ageRes'),
                  recordResPlus = pullTsVariable(lipd,'ageResPlus'),
                  climInterp    = pullTsVariable(lipd,'climateInterpretation1_variable'))

plotRange <- ggplot(proxyDf)+
  geom_rect(aes(xmin = 4000, xmax = 12000, ymin = -Inf, ymax = Inf), fill = failColors[3],alpha=0.3) +
  geom_histogram(aes(recordRange,fill=archive),alpha=0.7,binwidth = 300) +
  scale_fill_manual(values=colors) +
  scale_x_continuous(name = "Record Length (years)",
                     limits=c(0,12000),expand=c(0,0),breaks=seq(0,12000,2000)) +
  scale_y_continuous(name = "Count of Records",oob=scales::squish,expand=c(0,0)) +
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = c(0.5,0.6))#legend.position = 'none')# 

plotResPlus <- ggplot(proxyDf)+
  geom_rect(aes(xmin = 0, xmax = 400, ymin = -Inf, ymax = Inf), fill = failColors[3],alpha=0.3) +
  geom_rect(aes(xmin = 400, xmax = 1000, ymin = -Inf, ymax = Inf), fill = failColors[2],alpha=0.3) +
  geom_histogram(aes(recordResPlus,fill=archive),alpha=0.7,binwidth = 50) +
  scale_fill_manual(values=colors) +
  scale_x_continuous(name = "Median Sample Resolution (years/sample)" , expand=c(0,0)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish,expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = c(0.5,0.6))#legend.position = 'none')# legend.position = c(0.5,0.7))

plotTimeData <- plotTimeAvailabilityTs(lipd,age.range = c(0,18000),step=200,group='PassFail')
plotTime <- ggplot(plotTimeData$data,aes(yvec,value))+
  geom_rect(aes(xmin = 0, xmax = 12000, ymin = -Inf, ymax = Inf), fill = "grey",alpha=0.3) +
  geom_area(alpha=1,aes(fill=group),color='Black',size=0.2)+
  scale_fill_manual(values=failColors[c(2,1,3)]) +
  scale_x_reverse(name = "Age (yr BP)", limits=c(18000,0),expand=c(0,0))  +
  scale_y_continuous(name = "Count of Records",expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))

proxyDataPrj   <- SpatialPointsDataFrame(proxyDf[,c("longitude", "latitude")], proxyDf, proj4string=CRS(PROJorig))
proxyDataPrj   <- spTransform(proxyDataPrj, CRSobj = PROJ)

dir2 <- '/Volumes/GoogleDrive/My Drive/zResearch/Manuscript/HoloceneHydroclimate/' #
LL  <- read.csv(file=file.path(dir2,'Data','Proxy',paste('proxyMetaData_',climVar,'.csv',sep=''))) %>%
  filter(archive=='LakeDeposits')
LLPrj   <- SpatialPointsDataFrame(LL[,c("longitude", "latitude")], LL, proj4string=CRS(PROJorig))
LLPrj   <- spTransform(LLPrj, CRSobj = PROJ)
refrenceSubset <-       subset(refregions, Acronym %in% proxyDf$ipccReg)
refrenceSubsetSelect <- subset(refregions, Acronym %in% (proxyDf %>% 
                                                         group_by(ipccReg) %>% 
                                                         summarize(count=n()) %>% 
                                                         filter(count >= 6))$ipccReg)


dataTable <- fortify(refrenceSubset)
proxyMapSites <- basemap +
  geom_map(data=refrenceSubset, map=dataTable, alpha=0.75, size=0.3, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id),fill=NA,linetype = "dashed") +
  geom_point(data= as.data.frame(LLPrj),aes(x=longitude.1 , y=latitude.1),color='black',size = 1) +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Fail"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[1],shape = 1, size = 1.5,stroke=0.5) +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Close"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[2],shape = 1, size = 3,stroke=1) +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Pass"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[3],shape = 1, size = 4.5,stroke=1.5) +
  coord_map(projection = PROJ) + 
  coord_cartesian(xlim = range(as.data.frame(proxyDataPrj)$longitude.1), ylim = range(as.data.frame(proxyDataPrj)$latitude.1))+
  scale_fill_manual(values=c(failColors[2],failColors[1],failColors[3])) +
  #scale_starshape_manual(values=plotSettings$shapes,name= 'Proxy Category') +
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        panel.background = element_rect(fill = 'white',color='Black'),
        legend.background =  element_rect(fill = alpha('white', 0.85),size=0.5),#alpha=0.5),
        legend.position  = 'none')#,legend.position = 'none')# legend.position = c(0.5,0.7))

compositePlot <- ggdraw(ggplot() +
    ggtitle(paste(dataset,' Summary Page \n (',
            'Pass = ',as.character(sum(proxyDf$PassFail == "Pass")),'; ',
            'Close (Sample Resolution < 1ka) = ',as.character(sum(proxyDf$PassFail == "Close")),'; ',
            'Fail = ',as.character(sum(proxyDf$PassFail == "Fail")),'; Black = Oxford Database)',sep='')) +
    theme(plot.background= element_rect(colour='White',fill='White'),
          panel.background = element_rect(colour='White',fill='White')))+
    draw_plot(plotTime, x = 0.6, y = 0.62, width = 0.4, height = 0.31) +
    draw_plot(plotRange, x = 0.6, y = 0.31, width = 0.4, height = 0.31) +
    draw_plot(plotResPlus, x = 0.6, y = 0, width = 0.4, height = 0.31) + 
    draw_plot(proxyMapSites,  x = 0,   y = 0, width = 0.6, height = 0.93)

#ggsave(compositePlot,filename = paste("C://Users/clh624/Desktop/",dataset,".png",sep=""),width = 10, height = 6, dpi = 600)
#ggsave(compositePlot,filename = paste("/Users/chrishancock/Desktop/",dataset,".png",sep=""),width = 10, height = 6, dpi = 600)

```


```{r}
lipd <- TS_Lake
failColors <- failColors
tso <- lipd[[2]]

for (i in c(1:length(lipd))){
  tso <- lipd[[i]]
  #
  #color
  if (tso$PassFail        ==  'Pass'){color = failColors[3]
  } else if (tso$PassFail == 'Close'){ color = failColors[2]
  } else{                              color = failColors[1]
  }
  #
  #Data
  data <- data.frame(
    Age = c(max(tso$age),tso$age[-1]-diff(tso$age)/2,tso$age[-1]-diff(tso$age)/2,min(tso$age)),
    Values = rep(tso$paleoData_values,2)
  )
  data <- data[order(data$Age),]
  #if (tso$climateInterpretation1_interpDirection == 'negative'){data$values<-data$values*-1}
  #
  #Plot Data from Holocene
  plt <- ggplot(data,aes(x=Age,y=Values)) +
    scale_x_continuous(limits=c(0,15000),expand=c(0,0))+
    coord_cartesian(xlim=c(12000,0)) +
    geom_hline(yintercept=c(0,mean(data$values,na.rm=TRUE))) +
    geom_line(color=color,size=2) + 
    geom_point(fill=color,color='black',size=1.3) + 
    theme_bw() +     
    theme(panel.grid = element_blank(),
          plot.background = element_rect(color='Black'))
  #
  #Map Data
  latlon <- data.frame(longitude=tso$geo_longitude,latitude=tso$geo_latitude)
  latlon <- SpatialPointsDataFrame(coords=latlon,data=latlon,proj4string=CRS(PROJorig))
  latlon <- spTransform(latlon,CRSobj = PROJ)
  lat = latlon@coords[2]
  lon = latlon@coords[1]
  map <- proxyMapSites + 
    geom_point(aes(x=lon,y=lat),color='gold',size=3) +
    theme(panel.grid = element_blank(),
          panel.background = element_rect(color='Black'))
  #
  #Base
  base <- ggplot()+
    scale_x_continuous(limits=c(0,1),expand=c(0,0)) +
    scale_y_continuous(limits=c(0,1),expand=c(0,0)) +
    theme_void()+
    theme(plot.background = element_rect(fill='White',color='Black'),
          panel.background = element_rect(fill='White',color='White'))
  #
  #Annotations
  h <- 0.45
  for (name in c('dataSetName','paleoData_TSid','archiveType',
                 'geo_latitude','geo_longitude','geo_elevation',
                 'paleoData_units','ageRange','ageResPlus','PassFail')){
      h <- h-0.038
      base <- base + 
        annotate("text", x = 0.52, y = h, label = paste(name,': ',sep=''),hjust = 0,size=3.5) +
        annotate("text", x = 0.65, y = h, label = tso[[name]],hjust = 0,size=3.5)    
  }
  $
  #Bring it all together
  summary <- ggdraw(base) + 
      draw_plot(plt, x = 0.001, y = 0.5, width = 1, height = 0.5) +
      draw_plot(map, x = 0.003, y = 0.003, width = 0.497, height = 0.497) 
  #
  #Save Figure
  ggsave(summary,filename=paste("/Users/chrishancock/Desktop/",dataset,"/",tso$geo_ipccRegion,'_',tso$geo_latitude,'_',tso$paleoData_TSid,".png",sep=""),width = 10, height = 6, dpi = 600)
}













summary



```

##################


```{r}
Dpoll   <- readLipd(file.path(dir,"LegacyClimate"))
```










```{r}
#Dataset Dashboard
dataset='LegacyClimate'
lipd <- TS_Poll
colors  = c("forestgreen")

proxyDf <- tibble(dataset       = pullTsVariable(lipd,'dataSetName'),
                  tsid          = pullTsVariable(lipd,'paleoData_TSid'),
                  PassFail      = pullTsVariable(lipd,'PassFail'),
                  longitude     = pullTsVariable(lipd,'geo_longitude'),
                  latitude      = pullTsVariable(lipd,'geo_latitude'),
                  ipccReg       = pullTsVariable(lipd,'geo_ipccRegion'),
                  archive       = pullTsVariable(lipd,'archiveType'),
                  proxy         = rep('Pollen',length(pullTsVariable(lipd,'archiveType'))),
                  minAge        = pullTsVariable(lipd,'ageMin'),
                  maxAge        = pullTsVariable(lipd,'ageMax'),
                  recordRange   = pullTsVariable(lipd,'ageRange'),
                  recordRes     = pullTsVariable(lipd,'ageRes'),
                  recordResPlus = pullTsVariable(lipd,'ageResPlus'),
                  AgeControlMax = pullTsVariable(lipd,'AgeControlMax'),
                  AgeControlN   = pullTsVariable(lipd,'AgeControlN'),
                  climInterp    = pullTsVariable(lipd,'climateInterpretation1_variable'))

plotRange <- ggplot(proxyDf)+
  geom_rect(aes(xmin = 4000, xmax = 12000, ymin = -Inf, ymax = Inf), fill = failColors[3],alpha=0.6) +
  geom_histogram(aes(recordRange,fill=proxy),alpha=0.7,binwidth = 300) +
  scale_fill_manual(values=colors) +
  scale_x_continuous(name = "Record Length (years)",
                     limits=c(0,12000),expand=c(0,0),breaks=seq(0,12000,2000)) +
  scale_y_continuous(name = "Count of Records",oob=scales::squish,expand=c(0,0)) +
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.position = 'none')#legend.title = element_blank())#,legend.position = c(0.5,0.6))#legend.position = 'none')# 

plotResPlus <- ggplot(proxyDf)+
  geom_rect(aes(xmin = 0, xmax = 400, ymin = -Inf, ymax = Inf), fill = failColors[3],alpha=0.6) +
  geom_histogram(aes(recordRes,fill=proxy),alpha=0.7,binwidth = 50) +
  scale_fill_manual(values=colors) +
  scale_x_continuous(name = "Median Sample Resolution (years/sample)" , expand=c(0,0)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish,expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.position = 'none')#legend.title = element_blank())#,legend.position = c(0.5,0.6))#legend.position = 'none')# legend.position = c(0.5,0.7))

plotAgeControl <- ggplot(proxyDf)+
  geom_rect(aes(xmin = 0, xmax = 3000, ymin = -Inf, ymax = Inf), fill = failColors[3],alpha=0.3) +
  geom_rect(aes(xmin = 3000, xmax = 4000, ymin = -Inf, ymax = Inf), fill = failColors[2],alpha=0.6) +
  geom_histogram(aes(AgeControlMax,fill=proxy),alpha=0.7) +
  scale_fill_manual(values=colors) +
  scale_x_continuous(name = "Max Holocene Gap in Holocene Age Resolution (years)" , expand=c(0,0)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish,expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.position = 'none')# legend.position = c(0.5,0.7))
        #legend.title = element_blank())#,legend.position = c(0.5,0.6))#

plotTimeData <- plotTimeAvailabilityTs(lipd,age.range = c(0,18000),step=200,group='PassFail')
plotTime <- ggplot(plotTimeData$data,aes(yvec,value))+
  geom_rect(aes(xmin = 0, xmax = 12000, ymin = -Inf, ymax = Inf), fill = "grey",alpha=0.3) +
  geom_area(alpha=1,aes(fill=group),color='Black',size=0.2)+
  scale_fill_manual(values=failColors[c(2,1,3)]) +
  scale_x_reverse(name = "Age (yr BP)", limits=c(18000,0),expand=c(0,0))  +
  scale_y_continuous(name = "Count of Records",expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))

proxyDataPrj   <- SpatialPointsDataFrame(proxyDf[,c("longitude", "latitude")], proxyDf, proj4string=CRS(PROJorig))
proxyDataPrj   <- spTransform(proxyDataPrj, CRSobj = PROJ)
refrenceSubset <-       subset(refregions, Acronym %in% proxyDf$ipccReg)
refrenceSubsetSelect <- subset(refregions, Acronym %in% (proxyDf %>% 
                                                         group_by(ipccReg) %>% 
                                                         summarize(count=n()) %>% 
                                                         filter(count >= 6))$ipccReg)



dataTable <- fortify(refrenceSubset)
dataTable$Count     <- NA
dataTable$CountName <- NA
dataTable$Region    <- NA

#Set Breaks and color scheme with lowest group as grey
figBreaks <- c(5,10,20,30,40,60,80)
figlabels <- c(paste("<",figBreaks[1]+1),
               paste(as.character(figBreaks[-length(figBreaks)]+1),"-",
                     as.character(figBreaks[-1])),
                      paste(">",figBreaks[length(figBreaks)]))
figPalette <- c("#CCCCCC",RColorBrewer::brewer.pal(n = 7, name = "YlOrBr"))

for (region in list(levels(refrenceSubset@data[["Acronym"]]))[[1]]){
  i = which(refregions@data[["Acronym"]]==region)
  count <- length(which(proxyDf$ipccReg==region))
  if (count == 0){         countName <- NA
  } else if (count <= figBreaks[1]){ countName <- 0
  } else if (count <= figBreaks[2]){ countName <- 1
  } else if (count <= figBreaks[3]){ countName <- 2
  } else if (count <= figBreaks[4]){ countName <- 3
  } else if (count <= figBreaks[5]){ countName <- 4
  } else if (count <= figBreaks[6]){ countName <- 5
  } else if (count <= figBreaks[7]){ countName <- 6
  } else {countName <- 7}
  dataTable$Count[which(dataTable$id==as.character(i-1))]     <- count
  dataTable$CountName[which(dataTable$id==as.character(i-1))] <- countName
  dataTable$Region[which(dataTable$id==as.character(i-1))]    <-region
}

proxyMapSites <- basemap +
  geom_map(data=refrenceSubset, map=dataTable, alpha=0.75, size=0.3, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id),fill=NA,linetype = "dashed") +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Fail"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[1],shape = 1, size = 1,stroke=0.5) +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Close"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[2],shape = 1, size = 2,stroke=1) +
  geom_point(data= as.data.frame(proxyDataPrj)[which(as.data.frame(proxyDataPrj)$PassFail=="Pass"),],
             aes(x=longitude.1 , y=latitude.1),color=failColors[3],shape = 1, size = 3,stroke=1.5) +
  coord_map(projection = PROJ) + 
  coord_cartesian(xlim = range(as.data.frame(proxyDataPrj)$longitude.1), ylim = range(as.data.frame(proxyDataPrj)$latitude.1))+
  #scale_starshape_manual(values=plotSettings$shapes,name= 'Proxy Category') +
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        panel.background = element_rect(fill = 'white',color='Black'),
        legend.background =  element_rect(fill = alpha('white', 0.85),size=0.5),#alpha=0.5),
        legend.position  = 'none')#,legend.position = 'none')# legend.position = c(0.5,0.7))
proxyMapSites

compositePlot <- ggdraw(ggplot() +
         ggtitle(paste(dataset,' Summary Page \n (',
                       'Pass = ',as.character(sum(proxyDf$PassFail == "Pass")),'; ',
                       '\n Close = ',as.character(sum(proxyDf$PassFail == "Close")),'(MaxAgeControlSpread<4ka with 5+ Dates); ',
                       '\n Fail = ',as.character(sum(proxyDf$PassFail == "Fail")),')',sep=''))+
         theme(plot.background= element_rect(colour='White',fill='White'),
               panel.background = element_rect(colour='White',fill='White')))+
    draw_plot(plotTime, x = 0.6, y = 0.74, width = 0.4, height = 0.25) +
    draw_plot(plotRange, x = 0.6, y = 0.5, width = 0.4, height = 0.25) +
    draw_plot(plotResPlus, x = 0.6, y = 0.25, width = 0.4, height = 0.25) + 
    draw_plot(plotAgeControl, x = 0.6, y = 0, width = 0.4, height = 0.25) + 
    draw_plot(proxyMapSites,  x = 0,   y = 0.15, width = 0.6, height = 0.7)

#ggsave(compositePlot,filename = paste("C://Users/clh624/Desktop/",dataset,".png",sep=""),width = 10, height = 6, dpi = 600)
ggsave(compositePlot,filename = paste("/Users/chrishancock/Desktop/",dataset,".png",sep=""),width = 10, height = 6, dpi = 600)



```

```{r}
```

















