---
goal: Plot age metadata to summarize holocene hydroclimate dataset
input: rdata for Temp12k and HC12k ts; refRegions
output: 4 figures (histogram of record length and resolution, graph of ts availability, and plot of number of records in each region)
author: chris hancock
---

###Settings in script
```{r}
#Set up directories and names
dataDir <-getwd()# '/Volumes/GoogleDrive/My Drive/zResearch/Manuscript/HoloceneHydroclimate/HoloceneHydroclimate/' #
figSize <- c(5,2.5)
figFont <- 'sans'
figText <- 8
#
```

###Load packages 
```{r warning=FALSE}
library(cowplot)
library(geoChronR)
library(ggplot2)
library(ggstar)
library(lipdR)
library(maptools)
library(proj4)
library(RColorBrewer)
library(rworldmap)
library(scales)
library(sp)
library(tidyverse)
```

###Input Data
```{r, warning=FALSE}
lipdData <- readRDS(file=file.path(dataDir,'Data','LiPD','lipdData.rds'))

PROJ       <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
PROJorig   <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
refregions <- readShapePoly(file.path(dataDir,'Data','IPCC_refRegions','IPCC-WGI-reference-regions-v4.shp'),
                            proj4string=CRS(PROJorig))
refregions <-  spTransform(refregions, CRSobj = PROJ)

countries  <- getMap("less islands")
countries  <- spTransform(countries,  CRSobj = PROJ)


```

###Add information about proxy categories
```{r}
climVar    <- 'HC'
lipdTSO <- lipdData[[climVar]]
proxyDf <- tibble(dataset       = pullTsVariable(lipdTSO,'dataSetName'),
                  tsid          = pullTsVariable(lipdTSO,'paleoData_TSid'),
                  longitude     = pullTsVariable(lipdTSO,'geo_longitude'),
                  latitude      = pullTsVariable(lipdTSO,'geo_latitude'),
                  ipccReg       = pullTsVariable(lipdTSO,'geo_ipccRegion'),
                  archive       = pullTsVariable(lipdTSO,'archiveType'),
                  proxy = pullTsVariable(lipdTSO,'paleoData_proxy'),
                  Category      = pullTsVariable(lipdTSO,'Category'),
                  CategorySpec  = pullTsVariable(lipdTSO,'CategorySpecific'),
                  recordRange   = pullTsVariable(lipdTSO,'ageRange'),
                  recordRes     = pullTsVariable(lipdTSO,'ageRes'),
                  recordResPlus = pullTsVariable(lipdTSO,'ageResPlus'),
                  season        = pullTsVariable(lipdTSO,'climateInterpretation1_seasonalityGeneral'),
                  climInterp    = pullTsVariable(lipdTSO,'climateInterpretation1_variable'),
                  source        = pullTsVariable(lipdTSO,'Source'),
                  direction     = pullTsVariable(lipdTSO,'climateInterpretation1_interpDirection'),
                  ka_0.5        = rep(NA, length(lipdTSO)),
                  ka_6          = rep(NA, length(lipdTSO)),
                  maxValAge     = rep(NA, length(lipdTSO)),
                  minValAge     = rep(NA, length(lipdTSO)),
                  )

for (tso in lipdTSO){
  i = which(proxyDf$tsid == tso$paleoData_TSid)
  vals = tso$paleoData_values[which(between(tso$age,0,12000))]
  ages =              tso$age[which(between(tso$age,0,12000))]
  for (ka in c(0.5,6)){
    proxyDf[i,paste('ka',ka,sep='_')]<-round(mean(vals[which(between(ages,1000*ka-500,1000*ka+500))],na.rm=TRUE),3)
  }
  if (!is.na(proxyDf[i,'direction']) & proxyDf[i,'direction']=='negative'){vals=vals*-1}
  proxyDf[i,'maxValAge'] <- mean(ages[which(vals==max(vals,na.rm=TRUE))])
  proxyDf[i,'minValAge'] <- mean(ages[which(vals==min(vals,na.rm=TRUE))])
}

tablelist <- vector(mode='list')
for (archive in unique(proxyDf$archive)){
  summary <- proxyDf[which(proxyDf$archive == archive),]%>% group_by(proxy) %>% summarise(n = n())
  tablelist[[paste(archive,'---------------------------')]] = as.data.frame(summary)
}

capture.output(tablelist, file = "ProxyArchiveCount_HoloceneHC.txt")
write.csv(proxyDf,file=file.path(dataDir,'Data',paste('proxyMetaData_',climVar,'.csv',sep='')))
```



```{r}


##############################
###Create list of color information
plotVals <- vector(mode='list')
plotVals$general  <- vector(mode='list')
plotVals$specific <- vector(mode='list')

plotVals$general$names  <- sort(unique(proxyMetaData$Category))
plotVals$general$colors <- c("powder blue","corn flower blue",
                             "dark blue","dark orchid","grey",
                             "forest green","firebrick")
plotVals$general$shapes <- c(12,21,15,5,13,14,11)

plotVals$specific$names <- sort(unique(proxyMetaData$CategorySpec))
plotVals$specific$colors<- c("powder blue","corn flower blue",
                             "dark blue","dark orchid","grey40","grey",
                            "forest green","yellowgreen","darkorange","lightcoral","firebrick")
plotVals$specific$shapes<- c(12,21,15,5,6,13,14,1,17,23,11)

plotSettings <- plotVals$specific

```

```{r}
save <- TRUE
pieData <- proxyMetaData %>% group_by(source) %>% summarise(n = n())  
pieData[which(pieData$source=='Arctic Holocene'),'source'] <- 'Arctic Holocene (Sundqvist et al., 2014)'
pieData[which(pieData$source=='iso2k'),'source'] <- 'Iso2k (Konecky et al., 2020)'
pieData[which(pieData$source=='Other'),'source'] <- 'Miscellaneous'
pieData[which(pieData$source=='SISAL'),'source'] <- 'SISAL (Comas-Bru et al., 2020)'
pieData[which(pieData$source=='Oxford Lake Levels Database'),'source'] <- 'Lake-Level Database (Street-Perrott et al., 1989)'
pieData[which(pieData$source=='Temp12k'),'source'] <- 'Temp12k (Kaufman et al., 2020)'
pieData[which(pieData$source=='wNA'),'source']  <- 'Western North America (Routson et al., 2021)'
pieData <- pieData %>% arrange(source)
pieData2 <- pieData %>% 
  mutate(csum = rev(cumsum(rev(n))), pos = n/2 + lead(csum, 1),pos = if_else(is.na(pos), n/2, pos))

#install.packages("ggrepel")
library(ggrepel)
pie <- ggplot(pieData2,aes(x="", y=n, fill=source)) +
  geom_bar(stat="identity", width=1, color= 'black') +
  coord_polar("y", start=0) +
  geom_label_repel(data = pieData2,
                   aes(y = pos, label = n),fill='White',
                   size = 2, nudge_x = 0.04, show.legend = FALSE) +
  scale_fill_manual(values=c("powder blue","dark blue","corn flower blue","forest green",
                             "grey","firebrick","yellowgreen","grey40"),name='Data Source') +
  theme_void() + 
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.15, "in"),
        legend.key.width = unit(0.15, "in"))
        #legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))
if (save) {
  ggsave(plot=pie , width = figSize[1], height = figSize[2], units='in', dpi = 600,
       filename = file.path(dataDir,"Figures","PlotProxySource.png"))
}
pie
```


Plot a histagram showing the median time difference between Holocene ages
```{r}
plotRes <- ggplot(proxyMetaData)+
  geom_vline(xintercept=median(proxyMetaData$recordRes),size=0.7) +
  geom_vline(xintercept=mean(proxyMetaData$recordRes),size=0.7,linetype=2) +
  geom_histogram(aes(recordRes,fill=CategorySpec),color='Black',alpha=0.7,binwidth = 30) +
  scale_fill_manual(values=plotSettings$colors) +
  scale_x_continuous(name="Median Sample Resolution (binwidth = 30 years)" ,
                     limits=c(0,1250), expand=c(0,0), breaks=seq(0,1250,150)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish, limits=c(0,110), expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')# 
plotRes
##############################
plotResPlus <- ggplot(proxyMetaData)+
  geom_vline(xintercept=median(proxyMetaData$recordResPlus),size=0.7) +
  geom_vline(xintercept=mean(proxyMetaData$recordResPlus),size=0.7,linetype=2) +
  geom_histogram(aes(recordResPlus,fill=CategorySpec),color='Black',alpha=0.7,binwidth = 30) +
  scale_fill_manual(values=plotSettings$colors) +
  scale_x_continuous(name = "Median Sample Resolution (binwidth = 30 years)" ,
                     limits=c(0,3000), expand=c(0,0), breaks=seq(0,1250,150)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish, limits=c(0,110), expand=c(0,0))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')# legend.position = c(0.5,0.7))
plotResPlus

if (save) {
  ggsave(plot=plotRes, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dataDir,"Figures","PlotProxyAgeRes.png"))
  ggsave(plot=plotResPlus, width = figSize[1], height = figSize[2], dpi = 600,
         filename = file.path(dataDir,"Figures","PlotProxyAgeResPlus.png"))
}
```


Plot a histagram based on record length over the Holocene
```{r}
plotRange <- ggplot(proxyMetaData)+
  geom_vline(xintercept=median(proxyMetaData$recordRange),size=0.7) +
  geom_vline(xintercept=mean(proxyMetaData$recordRange),size=0.7,linetype=2) +
  geom_histogram(aes(recordRange,fill=CategorySpec),color='Black',alpha=0.7,binwidth = 300) +
  scale_fill_manual(values=plotSettings$colors) +
  scale_x_continuous(name = "Record Length (binwidth = 300 years)",
                     limits=c(3000,12000),expand=c(0,0),breaks=seq(3000,12000,1200)) +
  scale_y_continuous(name = "Count of Records",oob=scales::squish,limits=c(0,120),expand=c(0,0)) +
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')# 

plotRange
if (save) {
  ggsave(plot=plotRange, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dataDir,"Figures","PlotProxyAgeRange.png"))
}
```

```{r}
#Plot a figure showiang temporal variability over the Holocene (using geochronR)
plotTimeData <- plotTimeAvailabilityTs(lipdTSO,age.range = c(0,12000),step=100,group='CategorySpecific')
plotTime <- ggplot(plotTimeData$data,aes(yvec,value))+
  geom_area(alpha=0.7,aes(fill=group),color='Black',size=0.2)+
  scale_fill_manual(values=plotSettings$colors) +
  scale_x_reverse(name = "Age (yr BP)", limits=c(12000,0),expand=c(0,0),
                  n.breaks=7,sec.axis = sec_axis(~.,labels=NULL))+
  scale_y_continuous(name = "Count of Records",limits=c(0,length(lipdTSO)),expand=c(0,0),
                     labels=seq(0,length(lipdTSO),100), breaks=seq(0,length(lipdTSO),100))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))

plotTime
if (save) {
  ggsave(plot=plotTime, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dataDir,"Figures","PlotTimeAvailability.png"))
}
```


```{r}
proxyDataPrj   <- SpatialPointsDataFrame(proxyMetaData[,c("longitude", "latitude")], proxyMetaData, proj4string=CRS(PROJorig))
proxyDataPrj   <- spTransform(proxyDataPrj, CRSobj = PROJ)
refrenceSubset <- subset(refregions, Acronym %in% proxyMetaData$ipccReg)
refrenceSubsetSelect <- subset(refregions, Acronym %in% (proxyMetaData %>% 
                                                           group_by(ipccReg) %>% 
                                                           summarize(count=n()) %>% 
                                                           filter(count >= 6))$ipccReg)

dataTable <- fortify(refrenceSubset)
dataTable$Count     <- NA
dataTable$CountName <- NA
dataTable$Region    <- NA

#Set Breaks and color scheme with lowest group as grey
figBreaks <- c(5,10,20,30,40,60,80)
figlabels <- c(paste("<",figBreaks[1]+1),
               paste(as.character(figBreaks[-length(figBreaks)]+1),"-",
                     as.character(figBreaks[-1])),
                      paste(">",figBreaks[length(figBreaks)]))
figPalette <- c("#CCCCCC",RColorBrewer::brewer.pal(n = 7, name = "YlOrBr"))

for (region in list(levels(refrenceSubset@data[["Acronym"]]))[[1]]){
  i = which(refregions@data[["Acronym"]]==region)
  count <- length(which(proxyMetaData$ipccReg==region))
  if (count == 0){         countName <- NA
  } else if (count <= figBreaks[1]){ countName <- 0
  } else if (count <= figBreaks[2]){ countName <- 1
  } else if (count <= figBreaks[3]){ countName <- 2
  } else if (count <= figBreaks[4]){ countName <- 3
  } else if (count <= figBreaks[5]){ countName <- 4
  } else if (count <= figBreaks[6]){ countName <- 5
  } else if (count <= figBreaks[7]){ countName <- 6
  } else {countName <- 7}
  dataTable$Count[which(dataTable$id==as.character(i-1))]     <- count
  dataTable$CountName[which(dataTable$id==as.character(i-1))] <- countName
  dataTable$Region[which(dataTable$id==as.character(i-1))]    <-region
}

```

#Map proxy data with IPCC regions
```{r}
basemap <- ggplot() +
  #Set Border around plot - probably not the best way to do this
  borders(aggregate(refregions, FUN=length), fill=NA, colour='black', size=2) +
  geom_map(data=refregions, map=fortify(refregions),
           aes(x=long, y=lat, group=group, map_id=id), fill="white", colour="white", size=1)+
  #Add Country data (basemap)
  geom_map(data=countries, map=fortify(countries),
           aes(x=long, y=lat, group=group, map_id=id), fill = "grey80",color="grey90",size=0.2) +
  coord_fixed(1) + 
  theme_void() 

df <- as.data.frame(proxyDataPrj)
for (i in plotSettings$names){
  df[which(df$CategorySpec==i),"CategorySpec"] #<- paste(i,'   (n=',length(which(df$CategorySpec==i)),')',sep='')
}
##############################
plotSettings <- plotVals$specific
#Plot Figure 1 proxy type for each site
proxyMapSites <- basemap +
  geom_map(data=refrenceSubset, map=dataTable, alpha=0.75, size=0.3, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id),fill=NA,linetype = "dashed") + 
  geom_star(data=df,aes(x=longitude.1 , y=latitude.1,starshape=CategorySpec, fill=CategorySpec),
            size=1.5,color='Black',alpha=1,starstroke=0.3) + 
  scale_fill_manual(values=plotSettings$colors,name= 'Proxy Category') +
  scale_starshape_manual(values=plotSettings$shapes,name= 'Proxy Category') +
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.background =  element_rect(fill = alpha('white', 0.85),size=0.5),#alpha=0.5),
        legend.margin = margin(c(0, 0.1, 0.05, 0.06), unit="in"),
        legend.key.height = unit(0.12, "in"),
        legend.key.width = unit(0.12, "in"),
        legend.position = c(0.15,0.28),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))



ggsave(plot=proxyMapSites, width = 6, height = 3.5, dpi = 600,
       filename = file.path(dataDir,"Figures",paste('PlotProxyTypeRegion_',climVar,'.png',sep='')))

```
```{r}
library(egg)
map <- ggarrange(proxyMapSites+theme(legend.position = c(0.05,0.3)), 
                 plotTime+theme(legend.position = 'none'),
                 ncol=1,widths=c(6),heights=c(3.5,1.5))

ggsave(plot=map, width = 6, height = 5, dpi = 600,
       filename = file.path(dataDir,"Figures",paste('PlotProxyTypeRegion_',climVar,'_withTime.png',sep='')))
```


```{r}
##############################
#Plot Figure 2 count by regions
proxyMapRegions <- basemap + 
  #Add refrence regions boundaries
  geom_map(data=refrenceSubset, map=dataTable, alpha=0.75, size=0.5, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id,fill=as.factor(dataTable$CountName))) +
  scale_fill_manual(values=figPalette,labels=figlabels)+
  #Add proxy sites
  geom_point(data=as.data.frame(proxyDataPrj), aes(x=longitude.1 , y=latitude.1), shape=1,size=0.8) +
  #Format Legend
  theme(legend.position = c(0.5,-0.01),
        legend.direction = "horizontal",
        legend.title=element_blank(),
        legend.background=element_rect(colour='black',size=0.4),
        legend.margin=margin(t = 1, r = 1, b = 3, l = -4.5, unit = "pt"),
        legend.key.width  = (unit(35, 'pt')),
        legend.key.height = (unit(5, 'pt')),
        legend.text = element_text(family='sans',size=8))

proxyMapRegions


ggsave(plot=proxyMapRegions, width = 6, height = (6/1.97+0.5), dpi = 600,
       filename = file.path(dataDir,"Figures",paste('PlotCountByRegion_',climVar,'.png',sep='')))
```





