---
goal: Plot Proxy Composites and compare to model simulations 
input: refregions, modelDF, proxyDF
output: too many figures
---

###Settings in script
```{r}
#Set up directories and names
dataDir <- getwd()
#
```

###Load packages 
```{r}
library(compositeR)
library(cowplot)
library(geoChronR)
library(maptools)
library(ncdf4)
library(lipdR)
library(rkt)
library(rworldmap)
library(scales)
library(tidyverse)
```

###Input Data
```{r, warning=FALSE}
lipdData <- readRDS(file=file.path(dataDir,'Data','LiPD','lipdData.rds'))
climVar    <- 'HC'
lipdTSO    <- lipdData[[climVar]]
climVarSettings    <- vector(mode='list')
climVarSettings$T  <- vector(mode='list')
climVarSettings$HC <- vector(mode='list')
climVarSettings$T$Pal  <- 'RdBu'
climVarSettings$T$Dir  <- 01
climVarSettings$T$Col  <- c("#FFEBEE","#FFCDD2","#EF9A9A") #reds
climVarSettings$T$Lab  <- "Cool <- (Standardized Anomoly) -> Warm"
climVarSettings$HC$Pal <- 'BrBG'
climVarSettings$HC$Dir <- 01
climVarSettings$HC$Col <- c("#E8EAF6","#303F9F","#1A237E") #indigo
climVarSettings$HC$Lab <- "Dry <- (Standardized Anomoly) -> Wet"
climVarSettings$HC$Lim <-  c(-2.5,2.5)
climVarSettings$HC$NAv <- 'light grey'
climVarSettings$HC$Seq <- seq(-2.2,2.2,0.4)

PROJ       <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
PROJorig   <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
refregions <- readShapePoly(file.path(dataDir,'Data','IPCC_refRegions','IPCC-WGI-reference-regions-v4.shp'),
                            proj4string=CRS(PROJorig))
refregions <-  spTransform(refregions, CRSobj = PROJ)

countries  <- getMap("less islands")
countries  <- spTransform(countries,  CRSobj = PROJ)
```


#Set settings based on climate variable (HC or T)
```{r}
regionData <- vector(mode='list')
regionData$proxy <- read.csv(file.path(dataDir,'Data','RegionComposites',climVar,'MedianTSbyRegion.csv'))
for (model in c('trace','hadcm','cmip6')){
  for (var in c('p-e_ANN','pre_ANN','tas_ANN','p-e_JJA','pre_JJA','tas_JJA')){
    regionData[[model]][[var]] <- read.csv(file.path(dataDir,'Data','Model','RegionTS',
                                                     paste('regional_',var,'_',model,'.csv',sep='')))
  }
}

regNames <- names(regionData$proxy)[-1]
binvec <- regionData$proxy$time
ageMin <- min(binvec)
ageMax <- max(binvec)

refrenceSubset <- subset(refregions, Acronym %in% regNames)


basemap <- ggplot() +
  #Set Border around plot - probably not the best way to do this
  borders(aggregate(refregions, FUN=length), fill=NA, colour='black', size=3) +
  geom_map(data=refregions, map=fortify(refregions),
           aes(x=long, y=lat, group=group, map_id=id), 
           fill="white", colour="white", size=1)+
  #Add Country data (basemap)
  geom_map(data=countries, map=fortify(countries),
           aes(x=long, y=lat, group=group, map_id=id), 
           fill = "grey80",color="grey90",size=0.2) +
  borders(database = refrenceSubset, fill=NA, colour='grey20') + 
  coord_fixed(1) + 
  theme_void() 
  
basemap
```



```{r}
xSize <- 0.085
ySize <- 0.06
nudgeVals <- data.frame(region=regNames,x=rep(0,length(regNames)),y=rep(0,length(regNames)))
nudgeVals[which(regNames=='ARO'),'x'] <- 0.025
nudgeVals[which(regNames=='ARO'),'y'] <- -0.01
nudgeVals[which(regNames=='CAF'),'x'] <- -0.04
nudgeVals[which(regNames=='CAR'),'x'] <- 0.007
nudgeVals[which(regNames=='CAR'),'y'] <- 0.04
nudgeVals[which(regNames=='NWN'),'x'] <- 0.0115
nudgeVals[which(regNames=='NWN'),'y'] <- 0.007
nudgeVals[which(regNames=='NEN'),'y'] <- -0.022
nudgeVals[which(regNames=='NEN'),'x'] <- 0.007
nudgeVals[which(regNames=='GIC'),'x'] <- 0.003
nudgeVals[which(regNames=='WNA'),'x'] <- -0.042
nudgeVals[which(regNames=='CNA'),'x'] <- 0.0035
nudgeVals[which(regNames=='ENA'),'x'] <- 0.042
nudgeVals[which(regNames=='SAM'),'y'] <- -0.02
nudgeVals[which(regNames=='NES'),'y'] <- 0.02
nudgeVals[which(regNames=='NSA'),'x'] <- 0.025
nudgeVals[which(regNames=='NSA'),'y'] <- 0.04
nudgeVals[which(regNames=='NAO'),'y'] <- -0.03
nudgeVals[which(regNames=='NAO'),'x'] <- 0.004
nudgeVals[which(regNames=='NEU'),'x'] <- 0.004
nudgeVals[which(regNames=='NEU'),'y'] <- 0.01
nudgeVals[which(regNames=='WCE'),'x'] <- -0.005
nudgeVals[which(regNames=='WSAF'),'x'] <- -0.022
nudgeVals[which(regNames=='ESAF'),'x'] <- 0.022
nudgeVals[which(regNames=='WCA'),'x'] <- -0.01
nudgeVals[which(regNames=='ESB'),'y'] <- 0.004
nudgeVals[which(regNames=='ESB'),'x'] <- -0.01
nudgeVals[which(regNames=='ECA'),'y'] <- 0.013
nudgeVals[which(regNames=='RFE'),'x'] <- -0.04
nudgeVals[which(regNames=='EPO'),'x'] <- -0.04
nudgeVals[which(regNames=='SAS'),'y'] <- -0.002
nudgeVals[which(regNames=='SAS'),'x'] <- -0.005
nudgeVals[which(regNames=='EAS'),'x'] <- 0.003
nudgeVals[which(regNames=='SEA'),'x'] <- -0.017
nudgeVals[which(regNames=='SAU'),'x'] <- -0.036
nudgeVals[which(regNames=='NZ'),'x'] <- -0.025
nudgeVals[which(regNames=='NZ'),'y'] <- 0.02


globalPlotOfRegions <- function(plotName,data=pltData,basemapPlot=basemap,regions=regNames,
                                nudgeDF=nudgeVals,w=xSize,h=ySize,
                                save=FALSE,
                                leg =climVarSettings[[climVar]],
                                path=file.path(dataDir,'Figures','')){
  map <- ggdraw() + draw_plot(basemap, x = 0, y = 0, width = 1, height = 1)
  for (reg in regions){
    xNudge  <- nudgeDF[which(regions==reg),'x']
    yNudge  <- nudgeDF[which(regions==reg),'y']
    map <- map + draw_plot(data[[reg]][[plotName]],
                           x = xNudge+(0.5-w/2)+0.5*data[[reg]]$plotLon/(9050504*2), 
                           y = yNudge+(0.5-h/2)+0.92*data[[reg]]$plotLat/(8625155*2), 
                           width = w, height = h)
  }
  if (save){
    ggsave(plot=map, width = 6, height = 6*0.5072, dpi = 600,
           filename = paste(path,'global_',climVar,'_',plotName,'.png',sep=''))
  }
  return(map)
}

```



























```{r}
#Create vector for adding plots for each region
#Load proxy and model data for each region
pltData <- vector(mode="list") 
#Calculate data to plot and connect it to region data
for (reg in regNames){
  pltData[[reg]] <- vector(mode="list")
  pltData[[reg]]$lipd <- filterTs(lipdTSO,paste('geo_ipccRegion',reg,sep='=='))
  #Load region composite matrix
  pltData[[reg]]$proxyEns <- read.csv(file.path(dataDir,'Data','RegionComposites',climVar,paste(reg,'.csv',sep='')))
  pltData[[reg]]$proxy    <- tibble(values=regionData$proxy[[reg]], time=regionData$proxy[['time']])
  #Get Lat/Lon information for labels associated with region and add to cluster dictionary
  Shp <- refregions@polygons[[which(refregions@data[["Acronym"]]==reg)]]@Polygons[[1]]
  pltData[[reg]]$plotLat <- Shp@labpt[2]
  pltData[[reg]]$plotLon <- Shp@labpt[1]
}

```


```{r warning=FALSE}
modelVar <- NA#'p-e'
if (!is.na(modelVar)){
  for (model in c('trace','hadcm')){
    modelData <- regionData[[model]][[paste(modelVar,'_ANN',sep='')]]
    for (reg in regNames){ 
      pltData[[reg]][[model]] <- tibble(values=modelData[,reg], time=modelData[,'X'])
    }
  }
  for (reg in regNames){ 
    pltData[[reg]]$cmip <- regionData$cmip[[paste(modelVar,'_ANN',sep='')]][,reg]
  } 
}

for (reg in regNames){
  timeAvail <- plotTimeAvailabilityTs(pltData[[reg]]$lipd,age.range=c(0,12000),
                                      group.var ='Category',step=100)$dat %>%
    group_by(yvec) %>% 
    summarise(count=sum(value),countPct=sum(value)/length(pltData[[reg]]$lipd))
  regEnsNA <- as.matrix(pltData[[reg]]$proxyEns)
  regEnsNA <- regEnsNA - as.numeric(apply(regEnsNA,2,mean,na.rm=TRUE))
  if (!is.na(modelVar)){
    scale    <- sd(regEnsNA,na.rm=TRUE)/mean(sd(pltData[[reg]][['trace' ]]$values,na.rm=TRUE),
                                             sd(pltData[[reg]][['hadcm' ]]$values,na.rm=TRUE))
    regEnsNA <- (regEnsNA/scale)*30
  } else{
    regEnsNA <- regEnsNA / (apply(regEnsNA,2,sd,na.rm=TRUE))
  }
  regEns   <- regEnsNA
  idx <- which(timeAvail$countPct<=0.5)
  idx_MH <- which(timeAvail$yvec==6000)
  if (length(idx > 0)){
    idx <- c(max(which(timeAvail$countPct[1:idx_MH]<=0.5),
                 1),
             min(which(timeAvail$countPct[idx_MH:length(timeAvail$countPct)]<=0.5)+idx_MH,
                 length(timeAvail$countPct)))
  regEns[1:idx[1],] <- NA 
  regEns[idx[2]:length(timeAvail$countPct),] <- NA 
  }
  plotlimit_set <- min(mean(c(max(abs(apply(regEns,1,median,na.rm=TRUE)),na.rm=TRUE),
                              max(abs(regEns),na.rm=TRUE))),8)
  plotlimit_set <- 5
  compBands <- vector(mode='list')
  compBands$na   <- plotTimeseriesEnsRibbons(X=binvec[2:122], Y=regEnsNA, alp=0.9,line.width=0.2,
                                             color.low='grey90',
                                             color.high='grey50',
                                             color.line='grey20') 
  compBands$vals <- plotTimeseriesEnsRibbons(X=binvec[2:122], Y=regEns, alp=0.9,line.width=0.2,
                                             color.low=climVarSettings[[climVar]]$Col[1],
                                             color.high=climVarSettings[[climVar]]$Col[2],
                                             color.line=climVarSettings[[climVar]]$Col[3]) 
  if (!is.na(modelVar)){
      compBands$vals <- compBands$vals + geom_boxplot(aes(x=6000,y=pltData[[reg]][['cmip']]*30),width=1000)
      hadcmTS <- pltData[[reg]][['hadcm']]
      hadcmTS$values <- 30*(hadcmTS$values - mean(hadcmTS$values[1:10],na.rm = TRUE))
      compBands$vals <- compBands$vals + 
        geom_line(aes(x=hadcmTS$time*100,y=hadcmTS$values),color='#827717',size=0.4,alpha=0.8)
      traceTS <- pltData[[reg]][['trace']]
      traceTS$values <- 30*(traceTS$values - mean(traceTS$values[1:10],na.rm = TRUE))
      compBands$vals <- compBands$vals + 
        geom_line(aes(x=traceTS$time*100,y=traceTS$values),color='firebrick4',size=0.4,alpha=0.8)
      plotlimit_set <- max(c(max(abs(traceTS$values[1:121]),abs(hadcmTS$values[1:121]))))
  }
  #plotlimit_set <-
  #
  #compBands$vals
  compBandPlt <- ggdraw() 
  for (plt in names(compBands)){
    compBands[[plt]] <- compBands[[plt]] + 
      scale_x_reverse(name = "Age (yr BP)", 
                      limits=c(12000,0), expand=c(0,0), n.breaks=7,sec.axis = dup_axis())+
      scale_y_continuous(name=paste('Standardized',climVar),
                      limits=c(plotlimit_set*-1000,plotlimit_set*1000),sec.axis = dup_axis(),
                      breaks = seq(-4,4,2))+
      coord_cartesian(xlim=c(12000,0), 
                      ylim=c(plotlimit_set*-1,plotlimit_set)) +
      theme_void() +
      theme(panel.border=element_rect(colour='Black',fill=NA,size=0.8),
            legend.position='none')
    if (plt == names(compBands)[1]){
      compBands[[plt]] <- compBands[[plt]] + 
        geom_hline(yintercept=0,size=0.15) +
        theme(panel.background=element_rect(colour='Black',fill='White',size=0.8),
              axis.ticks=element_line(color = 'black',size=0.2),
              axis.ticks.length=unit(-4,"pt"))
    }
    compBandPlt <- compBandPlt + draw_plot(compBands[[plt]], x = 0, y = 0, width = 1, height = 1)
  } 
  pltData[[reg]]$compBandPlt <- compBandPlt
  #
}

#pltData[['EAS']]$compBandPlt
compBandPlt <- globalPlotOfRegions('compBandPlt',save=FALSE)
#compBandPlt

ggsave(plot=compBandPlt, width = 19, height = 9, dpi = 600,
           filename = paste(file.path(dataDir,'Figures','global_'),modelVar,'_compBandPlt.png',sep=''))
```

```{r}
compBandPltLegend <- ggplot() +
      geom_line(aes(x=seq(0,12000,200),
                    y=sample(seq(2,4,0.01),length(seq(0,12000,200))),color = '  Proxy (>50% Records)'),
                    size=0.6,alpha=0.7) +
      geom_line(aes(x=seq(0,12000,200),
                    y=sample(seq(0,2,0.01),length(seq(0,12000,200))),color = ' Proxy (<50% Records)'),
                    size=0.6,alpha=0.7) +
      geom_line(aes(x=seq(0,12000,200),
                    y=sample(seq(-2,0,0.01),length(seq(0,12000,200))),color = ' TraCE-21ka'),
                    size=0.6,alpha=0.5) +
      geom_line(aes(x=seq(0,12000,200),
                    y=sample(seq(-4,-2,0.01),length(seq(0,12000,200))),color = 'HadCM3'),
                    size=0.6,alpha=0.5) +
      scale_x_reverse(name = "Age (yr BP)", 
                      limits=c(12000,0), expand=c(0,0), n.breaks=7,sec.axis = dup_axis(name=''))+
      scale_y_continuous(name=paste('Standardized Anomaly'),
                      limits=c(plotlimit_set*-1000,plotlimit_set*1000),
                      breaks = seq(-4,4,2),sec.axis = dup_axis(name='Wet <-     -> Dry'))+
      coord_cartesian(xlim=c(12000,0), 
                      ylim=c(plotlimit_set*-1,plotlimit_set)) +
      scale_color_manual(values=c(climVarSettings[[climVar]]$Col[2],'grey50','fire brick','goldenrod'),
                         labels=c('Proxy (>50%)','Proxy (<50%)','TraCE (Ann P)','HadCM3 (Ann P)')) +
      theme_bw() + 
      theme(text = element_text(family='sans',size=18),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.2, 0.2, 0.2, 0.2), "in"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.title = element_blank(),
        legend.key.height = unit(0.6, "in"),
        legend.key.width = unit(0.4, "in"))
ggsave(plot=compBandPltLegend, width = 9, height = 4, dpi = 600,
           filename = paste(file.path(dataDir,'Figures','global'),climVar,'_compBandPltLegend.png',sep=''))
#pltData[['EAS']]$compBandPlt + theme(legend.position=c(0,0)) 
```







































```{r}
for (reg in regNames){
  stripepltData <- bin(pltData[[reg]]$proxy$time, pltData[[reg]]$proxy$values, 
                        bin.vec=seq(ageMin,ageMax,1000), bin.fun = mean)
  pltData[[reg]]$StripePlot <- ggplot(stripepltData,aes(x,rep(1, 12,color=y),fill= y)) +
    scale_x_reverse(name="Age (yr BP)", limits=c(ageMax,ageMin), expand=c(0,0)) +
    scale_y_continuous(limits=c(0,1), expand=c(0,0)) +
    geom_col(width=1000,show.legend = FALSE) +
    scale_fill_distiller(palette=  climVarSettings[[climVar]]$Pal, 
                         na.value= climVarSettings[[climVar]]$NAv, 
                         limits=   climVarSettings[[climVar]]$Lim, 
                         breaks=   climVarSettings[[climVar]]$Seq,
                         direction=climVarSettings[[climVar]]$Dir, 
                         oob=squish, guide=guide_coloursteps(show.limits=FALSE)) +
    theme_void() + 
    theme(panel.border=element_rect(color='black',fill=NA,size=1),
          legend.position = "none")
}
leg <- climVarSettings[[climVar]]
StripePlot <- globalPlotOfRegions('StripePlot',save=FALSE)
legendPlt <- ggplot(data=data.frame(x=leg$Seq),aes(x=x,y=x,fill=x)) + 
  geom_point(alpha=0) +
  scale_fill_distiller(palette=leg$Pal,na.value=leg$NAv,limits=leg$Lim,breaks=leg$Seq,direction=leg$Dir,oob=squish, 
                       guide=guide_coloursteps(show.limits=FALSE,frame.colour = "black",frame.linewidth=1,
                                               ticks=TRUE,ticks.colour = "black",ticks.linewidth=1)) +
  geom_text(aes(x=0,y=1.6,label=c(leg$Lab)),color='black',size=1.5,family="sans", fontface="bold") + 
  theme_void() + 
   theme(plot.background=element_rect(color='black',fill='white',size=1),
         legend.position=c(0.5,0.4), aspect.ratio = 0.12, legend.direction='horizontal',
         legend.key.width  =(unit(40, 'points')), legend.key.height = (unit(10, 'points')),
         legend.text =element_text(size=4,family="sans"), legend.spacing.y = unit(2, "points"),
         legend.title=element_blank()) 
    #       
    #       
StripePlot <- StripePlot + draw_plot(legendPlt, x = 0.1, y = 0.1, width=0.8,height=0.12)
ggsave(plot=StripePlot, width = 6, height = 6*0.5072, dpi = 600,
           filename = paste(file.path(dataDir,'Figures','global'),climVar,'_StripePlot.png',sep=''))

```








```{r}


for (reg in regNames)){
  print(reg)
  compBandPltModel <- pltData[[reg]]$compBandPlt
  for (model in c('trace')){
    if (model == 'trace'){
      lc <- 'firebrick'
    } else if (model == 'hadcm'){
      lc <- 'goldenrod'
    }
    modelTSreg <- ggplot() + 
      geom_line(aes(x=seq(0,12000,100),
                    y=(modelTS[[model]][,reg]-mean(modelTS[[model]][,reg]))/sd(modelTS[[model]][,reg])),
                    color = lc, size=1,alpha=0.5) +
      scale_x_reverse(name = "Age (yr BP)", 
                          limits=c(12000,0), expand=c(0,0), n.breaks=7,sec.axis = dup_axis())+
      scale_y_continuous(name=paste('Standardized',climVar),
                          limits=c(plotlimit_set*-1000,plotlimit_set*1000),sec.axis = dup_axis(),
                          breaks = seq(-4,4,2))+
      coord_cartesian(xlim=c(12000,0), 
                          ylim=c(plotlimit_set*-1,plotlimit_set)) +
      theme_void() +
      theme(panel.border=element_rect(colour='Black',fill=NA,size=0.8))
    #
    compBandPltModel<-compBandPltModel + draw_plot(modelTSreg, x = 0, y = 0, width = 1, height = 1)
  }
  pltData[[reg]]$compBandPltModel <- compBandPltModel
}


compBandPltModel <- globalPlotOfRegions('compBandPltModel',save=FALSE)
#compBandPltModel
ggsave(plot=compBandPltModel, width = 6, height = 6*0.5072, dpi = 600,
      filename = paste(file.path(dataDir,'Figures','global'),climVar,'_compBandPltModel',sep=''))
             
```




```{r}

pc <- 2
dataTable <- fortify(refrenceSubset)
dataTable$Count     <- NA
for (reg in list(levels(refrenceSubset@data[["Acronym"]]))[[1]]){
  i = which(refregions@data[["Acronym"]]==reg)
  loading <- apply(pca[["loadings"]][,pc,],1,median,na.rm=TRUE)[which(regNames==reg)]
  dataTable$Count[which(dataTable$id==as.character(i-1))] <- loading
}
  
pcMapplot <- basemap + 
  #Add refrence regions boundaries
  geom_map(data=refrenceSubset, map=dataTable, alpha=0.75, size=0.5, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id,fill=dataTable$Count)) +
  scale_fill_binned(type = "viridis",name =paste('Loading (PC',pc,')',sep='')) + 
  theme(text = element_text(family='sans',size=12),
        plot.background = element_rect(fill = 'white',color='White'),
        plot.margin = unit(c(0.25, 0.25, 0.2, 0.2), "in"),
        legend.position = c(0.5,0.12),
        legend.direction='horizontal',
        legend.box.background=element_rect(fill = 'white',color='Black'),
        legend.box.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"),
        legend.key.width=unit(30, 'points'),
        legend.key.height=unit(8, 'points'))

pcTSplot <- ggplot() + 
  geom_line(aes(x=pca[["age"]]/1000,y=apply(pca[["PCs"]][,pc,],1,median,na.rm=TRUE)),
            color='Black',size=1)+
  labs(x='Age (yr BP)',y='Dry <    > Wet',subtitle=paste('PC',pc,sep='')) +
  theme_bw() +
  scale_x_reverse(name = "Age (ka BP)", 
                  limits=c(12,0), expand=c(0,0), n.breaks=7) +
  theme(text = element_text(family='sans',size=18),
        plot.background = element_rect(fill = 'white',color='White'),
        plot.margin = unit(c(0.25, 0.25, 0.2, 0.2), "in")) 
  
ggsave(plot=pcTSplot, width = 6, height = 3, dpi = 600,
      filename = paste(file.path(dataDir,'Figures','global_PC'),pc,'_TS.png',sep=''))
ggsave(plot=pcMapplot, width = 6, height = 3.5, dpi = 600,
      filename = paste(file.path(dataDir,'Figures','global_PC'),pc,'_Map.png',sep=''))

#which(regNames=reg)


#Load PCA data
pca <- readRDS(file.path(dataDir,'Data','RegionComposites','PCA','pcaHC12k.rds'))
  #plotPcaEns(pca)



```


































```
reg <- 'EAS'
for (region in 'EAS'){
  timeAvail <- plotTimeAvailabilityTs(pltData[[reg]]$lipd,age.range=c(ageMin,ageMax),
                                      group.var ='Category',step=200)$dat %>%
    group_by(yvec) %>% 
    summarise(count=sum(value),countPct=sum(value)/length(pltData[[reg]]$lipd))
  regionData <- as.matrix(pltData[[reg]]$compMatix)
  regionDataNA <- regionData
  regionDataNA[which(timeAvail$countPct>=0.5),] <- NA
  plotlimit_set <- 4 
  CompBands <- plotTimeseriesEnsRibbons(X=binvec, Y=regionData, alp=0.9,line.width=0.2,
                                        color.low=climVarSettings[[climVar]]$Col[1],
                                        color.high=climVarSettings[[climVar]]$Col[2],
                                        color.line=climVarSettings[[climVar]]$Col[3]) 
  CompBandsNA <- plotTimeseriesEnsRibbons(X=binvec, Y=regionDataNA, alp=0.9,line.width=0.2,
                                          color.low='grey20',
                                          color.high='grey40',
                                          color.line='black')
  plot <- CompBandsNA + 
                                          
                                          
}
    scale_x_reverse(name = "Age (yr BP)", 
                    limits=c(ageMax,ageMin), expand=c(0,0), n.breaks=7)+
    scale_y_continuous(name=paste('Standardized',climateVariable),
                       limits=c(plotlimit_set*-1000,plotlimit_set*1000))+
    coord_cartesian(xlim=c(ageMax,ageMin), 
                    ylim=c(plotlimit_set*-1,plotlimit_set)) +
    theme_void() +
    theme(panel.background=element_rect(colour='Black',fill='lightgrey'),
          panel.border=element_rect(colour='Black',fill=NA),
          panel.grid.major=element_line(colour='Grey'))
  #
```

  
Plot Proxy Composites ('CompBands')
Plot Porxy Composites vs model ('ProxyModel) 
```{r}  
for (reg in regNames){
  
  
  ##round(abs(max(pltData[[region]]$ts$values))*2)/2
+
    scale_x_reverse(name = "Age (yr BP)", 
                    limits=c(ageMax,ageMin), expand=c(0,0), n.breaks=7)+
    scale_y_continuous(name=paste('Standardized',climateVariable),
                       limits=c(plotlimit_set*-1000,plotlimit_set*1000))+
    coord_cartesian(xlim=c(ageMax,ageMin), 
                    ylim=c(plotlimit_set*-1,plotlimit_set)) +
    theme_void() +
    theme(panel.background=element_rect(colour='Black',fill='lightgrey'),
          panel.border=element_rect(colour='Black',fill=NA),
          panel.grid.major=element_line(colour='Grey'))
  #
  pltData[[region]]$ProxyModel <- pltData[[region]]$CompBands +
    geom_line(data=pltData[[region]][['trace']], 
              aes(x=time,y=values), 
              color = 'firebrick', size=0.2) +
    geom_line(data=pltData[[region]][['hadcm']], 
              aes(x=time,y=values), 
              color = 'goldenrod', size=0.2)
  #
}
pltData[['EAS']]$ProxyModel
```

#Calculate and store slopes (rkt) for proxy and model data across multiple timeseries
```{r}
sigThreshold <- 0.01
nDiv <- 3
for (region in names(compositeData)[-1]){
  #Calculate slopes for proxy and model data
  pltData[[region]]$slopeData <- vector(mode='list')
  barColor = c()
  div = 1
  while(div <= nDiv){
    for (time in 1:div){
      maxKa  <- 12-((time-1)*(12/div))
      minKa  <- 12-(time*(12/div))
      timeperiod <- paste(maxKa,'_',minKa,sep='')
      timeperiodDF <- data.frame(ageMax = maxKa*1000, ageMin = minKa*1000)
      for (select in c('proxy','trace','hadcm')){
        dataSelect <- pltData[[region]][[select]] %>%
          filter(time >= minKa*1000 & time <= maxKa*1000)
        slopeCalc  <- rkt(dataSelect$time,dataSelect$values*-1)
        if (slopeCalc$sl < sigThreshold){
          slopeVal <- slopeCalc$B
        } else{slopeVal <- NA}
        timeperiodDF[paste(select,'_slopeSig',sep='')] <- slopeCalc$sl
        timeperiodDF[paste(select,'_slopeSen',sep='')] <- slopeCalc$B * 3000
        timeperiodDF[paste(select,'_slopeVal',sep='')] <- slopeVal    * 3000
      }
      barColor <- c(barColor,rep(timeperiodDF$proxy_slopeVal,12/div))
      pltData[[region]]$slopeData[[timeperiod]] <- timeperiodDF
    }
    div <- div+1
  }
  pltData[[region]]$slopeData[['barColor']]<- barColor 
}
```

Plot proxy slopes by timeslice ('CompBands')
Plot proxy and model slopes comparison ('CompBands')


```{r}


```

```{r}


for (region in names(compositeData)[-1]){

  pltData[[region]]$SlopeFig <- ggplot(slopeData,
                                        aes(x=barLocation, y=barWidth ,fill=barColor)) +
      geom_bar(width=1, stat="identity",show.legend = FALSE) +
      scale_x_continuous(name="Age (yr BP)", expand=c(0,0)) +
      scale_y_continuous(limits=c(0,nDiv), expand=c(0,0)) +
      scale_fill_distiller(palette=colorPalette, 
                           na.value=colorNAval, 
                           limits=colorLimits, 
                           breaks=colorSeq,
                           direction=colorDir, 
                           oob=squish, 
                           guide=guide_coloursteps(show.limits=FALSE)) +
      geom_hline(yintercept=1:nDiv,size=0.2,alpha=0.7) +
      theme_void() + 
    theme(panel.border=element_rect(color='black',fill=NA,size=0.5))
  for (time in c('12_0','12_6','6_0')){
    pieChartData <- data.frame(
      group=c(pltData[[region]]$slopeData[[time]]$proxy_slopeVal,
              pltData[[region]]$slopeData[[time]]$trace_slopeVal,
              pltData[[region]]$slopeData[[time]]$hadcm_slopeVal),
      value=c(12,6,6))
    pltData[[region]][[paste('SlopeFig_',time,sep='')]] <- ggplot(pieChartData, 
                                                                    aes(x="",y=value, 
                                                                        fill=group)) +
      geom_bar(stat="identity", width=1, color="Black",show.legend = FALSE) +
      coord_polar("y", start=0) +
      scale_fill_distiller(palette=colorPalette, 
                           na.value=colorNAval, 
                           limits=colorLimits, 
                           breaks=colorSeq,
                           direction=colorDir, 
                           oob=squish, guide=guide_coloursteps(show.limits=FALSE)) +
      theme_void()
  }
}
pltData[['EAS']][['SlopeFig']]
pltData[['EAS']][['SlopeFig_12_6']]

```


```{r}
cmipData <- read.csv(paste(dataDir,'DataFiles/cmip6/ann_P',sep=''))[-1] %>%
  select('region', 'name', everything())

for (region in names(compositeData)[-1]){
  i0 <- which(pltData[[region]][['proxy']]$time <= 1200)
  i6 <- which(pltData[[region]][['proxy']]$time <= 6500 & 
              pltData[[region]][['proxy']]$time >= 5500)
  Proxy <- mean(pltData[[region]][['proxy']]$values[i6]) - mean(pltData[[region]][['proxy']]$values[i0])
  HadCM <- mean(pltData[[region]][['hadcm']]$values[i6]) - mean(pltData[[region]][['hadcm']]$values[i0])
  TraCE <- mean(pltData[[region]][['trace']]$values[i6]) - mean(pltData[[region]][['trace']]$values[i0])
  colorData <- c(rep(Proxy,5),HadCM,TraCE,
                 as.numeric(cmipData[which(cmipData$region==region),3:ncol(cmipData)])*86400)
  cmipPlt <- data.frame(col=rep(-1,20),row=rep(seq(1:5),4),color=colorData)
  cmipPlt <- ggplot(cmipPlt,aes(x=row, y=col,fill=color*10))+
    geom_bar(width=1, stat="identity",show.legend = FALSE) +
    scale_y_continuous(limits=c(-4,0), expand=c(0,0)) +
    scale_x_continuous(limits=c(0.5,5.5), expand=c(0,0)) +
    scale_fill_distiller(palette=colorPalette, 
                             na.value=colorNAval, 
                             limits=colorLimits, 
                             #breaks=colorSeq,
                             direction=colorDir, 
                             oob=squish, 
                             guide=guide_coloursteps(show.limits=FALSE)) +
    geom_hline(yintercept=-1,size=0.7) +
    geom_segment(aes(x=0.5,xend=2.5,y=-2,yend=-2),size=0.7) +
    geom_segment(aes(x=2.5,xend=2.5,y=-1,yend=-2),size=0.7) + 
    theme_void()
  pltData[[region]]$cmipPlt <- cmipPlt
}
pltData[['EAS']]$cmipPlt
```




```{r}
for (plotType in c('cmipPlt')){#},'SlopeFig','StripePlot',#'plotTS'
                   #'UncertaintyBands','ProxyModel','pieAgreement')){ #'corOutFig'
  #Some more settings
  #Do the plotting thing
  if (plotType %in% c('plotTS','UncertaintyBands','ProxyModel','cmipPlt',
                      'StripePlot','SlopeFig','corOutFig')){
    if (plotType %in% c('StripePlot','SlopeFig')){
      mapPlot <- ggdraw() + draw_plot(baseMapScale, x = 0, y = 0, width = 1, height = 1)
    } else{
      mapPlot <- ggdraw() + draw_plot(baseMap,      x = 0, y = 0, width = 1, height = 1)
    }
    for (region in names(compositeData)[-1]){
      if (plotType=='corOutFig' & region == 'NWS') next
      xNudge  <- 0
      yNudge  <- 0
      stripeX <- 0.08
      stripeY <- 0.055
      if (       region == 'ENA'){
        yNudge <- 0.045
      } else if (region == 'WNA'){
        yNudge <- 0.03
      } else if (region == 'ECA'){
        yNudge <- 0.01
      } else if (region == 'CNA'){
        yNudge <- -0.01
      } else if (region == 'SAU'){
        xNudge <- -0.01
      } else if (region == 'WCA'){
        xNudge <- -0.005
      }
      mapPlot <- mapPlot + 
        draw_plot(pltData[[region]][[plotType]],
              y = yNudge+(0.5-stripeY/2)+0.80*pltData[[region]]$plotLat/(8625155*2),
              x = xNudge+(0.5-stripeX/2)+0.48*pltData[[region]]$plotLon/(9050504*2),
              width = stripeX, height = stripeY)
    }
    mapPlot
    ggsave(paste(plotType,'_',climateVariable,'.png',sep=''),mapPlot,
         path=paste(dataDir,'Figures/',sep=''),
         width=6,height=(6/1.97+0.5),dpi = 600,device='png')
  } else if (plotType=='pieAgreement'){
    for (timeperiod in c('12_0','12_6','6_0')){
      plotType <- paste('SlopeFig_',timeperiod,sep='')
      mapPlot <- ggdraw() + draw_plot(baseMapScale, x = 0, y = 0, width = 1, height = 1)
      for (region in names(compositeData)[-1]){
        xNudge  <- 0
        yNudge  <- 0
        stripeX <- 0.12
        stripeY <- 0.12
        if (       region == 'ENA'){
          xNudge <- 0.01
        } else if (region == 'WNA'){
          xNudge <- -0.02
        } else if (region == 'MED'){
          xNudge <- -0.015
        } else if (region == 'WCE'){
          xNudge <- 0.02
        } else if (region == 'SAH'){
          xNudge <- -0.04
        } else if (region == 'WCA'){
          xNudge <- 0
        } else if (region == 'ECA'){
          xNudge <- -0.02
          yNudge <- 0.01
        } else if (region == 'ESB'){
          xNudge <- 0.01
        } else if (region == 'TIB'){
          xNudge <- 0.025
          yNudge <- -0.01
        } else if (region == 'SAS'){
          yNudge <- -0.025
        } else if (region == 'NCA'){
          xNudge <- -0.01
          yNudge <- -0.01
        } else if (region == 'NEAF'){
          yNudge <- 0.02
        } else if (region == 'SEAF'){
          yNudge <- -0.02
        }
        mapPlot <- mapPlot + 
          draw_plot(pltData[[region]][[paste('SlopeFig_',timeperiod,sep='')]],
                y = yNudge+(0.5-stripeY/2)+0.80*pltData[[region]]$plotLat/(8625155*2),
                x = xNudge+(0.5-stripeX/2)+0.48*pltData[[region]]$plotLon/(9050504*2),
                      width = stripeX, height = stripeY)
      }
      mapPlot
      ggsave(paste(plotType,'_',climateVariable,'.png',sep=''),mapPlot,
           path=paste(dataDir,'Figures/',sep=''),
           width=6,height=(6/1.97+0.5),dpi = 600,device='png')
    } 
  }
}
    




```










```{r}
for (region in names(compositeData)[-1]){
  clusterSelect <- clusterGroups[which(clusterGroups$Acronym==region),]
  ffTS <- fTS[which(pullTsVariable(fTS,"paleoData_TSid") %in% clusterSelect$TSid)]
  ls  <- map_dbl(ffTS,function(x) sum(!is.na(x$paleoData_values) & !is.na(x$age)))
  ls2 <- map_dbl(ffTS,function(x) length(x$paleoData_values))
  ffTS <- ffTS[which(ls >= 9 & ls2 >= 9)]
    #
    #Print update on progress
  colorVals <- sort(unique(pullTsVariable(ffTS,'Category')))
  colorVals <- str_replace(colorVals,"Glacier Ice","powder blue")
  colorVals <- str_replace(colorVals,"Lake Deposits","corn flower blue")
  colorVals <- str_replace(colorVals,"Lake Sediment d18O","dark blue")
  colorVals <- str_replace(colorVals,"Leaf Wax dD","dark orchid")
  colorVals <- str_replace(colorVals,"Other","grey")
  colorVals <- str_replace(colorVals,"Pollen","forest green")
  colorVals <- str_replace(colorVals,"Speleothem" ,"firebrick")
  #Plot a figure showiang temporal variability over the Holocene (using geochronR)
  plotTimeData <- plotTimeAvailabilityTs(ffTS,age.range = c(0,12000), 
                                         age.var="age", group='Category')
  pltData[[region]][['plotTS']] <- ggplot(plotTimeData$data,aes(yvec,value))+
    geom_area(alpha=0.7,aes(fill=group))+
    scale_fill_manual(values	= colorVals)+
    scale_x_reverse(limits=c(12000,0),expand=c(0,0))+
    scale_y_continuous(limits=c(0,length(ffTS)+((80-length(ffTS))/4)),
                       breaks=seq(0,80,10),expand=c(0,0))+
    theme_void()+
    theme(legend.position = "none") + 
    theme(panel.background=element_rect(colour='Black',fill='white'),
          panel.border=element_rect(colour='Black',fill=NA),
          panel.grid.major=element_line(colour='Grey'))
}
pltData[['EAS']][['plotTS']]

```









```{r}

```


```{r}

modelproxyCor <- function(proxyDF,traceDF,hadcmDF,binstep){
  corOut <- vector(mode='list')
  corOut['trace'] <- corEns(time.1   = traceDF$time,
                            values.1 = proxyDF,
                            time.2   = traceDF$time,
                            values.2 = traceDF$values,
                            bin.step = binstep)
  corOut['hadcm'] <- corEns(time.1   = hadcmDF$time,
                            values.1 = proxyDF,
                            time.2   = hadcmDF$time,
                            values.2 = hadcmDF$values,
                            bin.step = binstep)
  corOut['model'] <- corEns(time.1   = traceDF$time,
                            values.1 = traceDF$values,
                            time.2   = hadcmDF$time,
                            values.2 = hadcmDF$values,
                            bin.step = binstep)
  return(corOut)
}

for (region in names(compositeData)[-1]){
  if (region == 'NWS')next
  corOut <- modelproxyCor(as.matrix(pltData[[region]]$compMatix)[,1:1000],
                                    pltData[[region]][['trace']],
                                    pltData[[region]][['hadcm']],500)
  pltData[[region]]$corOut <- corOut
  colorVals <- c()
  for (cor in c('trace','hadcm','model')){
    if (median(corOut[[cor]]$pIsospectral,na.rm=TRUE) < 0.1){
      colorVals <- c(colorVals,median(corOut[[cor]]$r,na.rm=TRUE))
    } else {colorVals <- c(colorVals,0)}
  }
  print(colorVals)
  pltData[[region]]$corOutFig <- ggplot(data.frame(colorVals=colorVals),aes(x=c(1,2,3), y=c(1,1,1) ,fill=colorVals)) +
      geom_bar(width=1, stat="identity",show.legend = FALSE) +
      scale_x_continuous(name="Age (yr BP)",limits=c(0.5,3.5),expand=c(0,0)) +
      scale_y_continuous(limits=c(0,1), expand=c(0,0)) +
      scale_fill_distiller(palette='Spectral', 
                           na.value='White', 
                           limits=c(-1,1), 
                           direction=colorDir) +
      geom_vline(xintercept=seq(1.5,2.5,1),size=0.2,alpha=0.7) +
      theme_void() + 
      theme(panel.border=element_rect(color='black',fill=NA,size=0.5))
}

  

```



