---
goal: Plot age metadata to summarize holocene hydroclimate dataset
input: figure settings variables not for temp12k
output: 4 figures (histogram of record length and resolution, graph of ts availability, and plot of number of records in each region)
author: chris hancock
---
###Load packages 
```{r warning=FALSE}
library(cowplot)
library(egg)
library(geoChronR)
library(ggrepel)
library(ggplot2)
library(ggstar)
library(lipdR)
library(maptools)
library(proj4)
library(RColorBrewer)
library(rworldmap)
library(scales)
library(sp)
library(tidyverse)
```

###Input Data
```{r, warning=FALSE}
save     <- FALSE
proxyDf <- read.csv(file=file.path(dir,'Data','Proxy',paste('proxyMetadata_',var,'.csv',sep='')))

```

###Pie Chart for Sproxy data source
```{r}

pieData <- proxyDf %>% group_by(source) %>% summarise(n = n())
names <- as.character(pieData$source)
names[which(names=='Arctic Holocene')]             <- 'Arctic Holocene (Sundqvist et al., 2014)'
names[which(names=='iso2k')]                       <- 'Iso2k (Konecky et al., 2020)'
names[which(names=='Other')]                       <- 'Miscellaneous'
names[which(names=='SISAL')]                       <- 'SISAL (Comas-Bru et al., 2020)'
names[which(names=='Oxford Lake Levels Database')] <- 'Lake-Level Database (Street-Perrott et al., 1989)'
names[which(names=='Liefert and Shuman, 2020')] <- 'NA Lake Level Database (Liefert and Shuman, 2020)'
names[which(names=='Temp12k')]                     <- 'Temp12k (Kaufman et al., 2020)'
names[which(names=='wNA')]                         <- 'Western North America (Routson et al., 2021)'

pieData <- pieData %>% arrange(source)

pieData2 <- pieData %>% 
  mutate(csum = rev(cumsum(rev(n))), pos = n/2 + lead(csum, 1),pos = if_else(is.na(pos), n/2, pos))

pie <- ggplot(pieData2,aes(x="", y=n, fill=source)) +
  geom_bar(stat="identity", width=1, color= 'black') +
  coord_polar("y", start=0) +
  geom_label_repel(data = pieData2,
                   aes(y = pos, label = n),fill='White',
                   size = 2, nudge_x = 0.04, show.legend = FALSE) +
  scale_fill_manual(values=c("powder blue","dark blue","corn flower blue","forest green",
                             "grey","firebrick","yellowgreen","grey40"),name='Data Source') +
  theme_void() + 
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.15, "in"),
        legend.key.width = unit(0.15, "in"))
        #legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))
if (save) {
  ggsave(plot=pie , width = figSize[1], height = figSize[2], units='in', dpi = 600,
       filename = file.path(dir,"Figures","PlotProxySource.png"))
}
pie
```


###Plot a histagram showing the median time difference between Holocene ages
```{r}
binsize = 25
plotRes <- ggplot(proxyDf)+
  geom_vline(xintercept=median(proxyDf$ageRes), size=0.8) +
  geom_vline(xintercept=mean(proxyDf$ageRes), size=0.8, linetype=2) +
  geom_histogram(aes(ageRes,fill=CategorySpec), color='Black', alpha=0.7, breaks = seq(0,max(proxyDf$ageRes,na.rm=TRUE)+binsize,binsize)) +
  scale_fill_manual(values=plotSettings$color) +
  scale_x_reverse(name="Median Proxy Sample Resolution (binwidth = binsize years)" ,
                     limits=c(max(proxyDf$ageRes,na.rm=TRUE)+binsize/2,0), expand=c(0,0), breaks=seq(0,max(proxyDf$ageRes,na.rm=TRUE),300)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish, limits=c(0,150), expand=c(0,0))+
  coord_flip()+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'White',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')#
  
plotRes
##############################
binsize<-100
plotResPlus <- ggplot(proxyDf)+
  geom_vline(xintercept=median(proxyDf$ageResPlus), size=0.8) +
  geom_vline(xintercept=mean(proxyDf$ageResPlus), size=0.8, linetype=2) +
  geom_histogram(aes(ageResPlus,fill=CategorySpec), color='Black', alpha=0.7, breaks = seq(0,max(proxyDf$ageResPlus,na.rm=TRUE)+binsize,binsize)) +
  scale_fill_manual(values=plotSettings$color) +
  scale_x_reverse(name="Median Proxy Sample Resolution (binwidth = binsize years)" ,
                     limits=c(max(proxyDf$ageResPlus,na.rm=TRUE)+binsize/2,0), expand=c(0,0), breaks=seq(0,max(proxyDf$ageResPlus,na.rm=TRUE),600)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish, limits=c(0,250), expand=c(0,0))+
  coord_flip()+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'White',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')# legend.position = c(0.5,0.7))
plotResPlus

if (save) {
  ggsave(plot=plotRes, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dir,"Figures","PlotProxyAgeRes.png"))
  ggsave(plot=plotResPlus, width = figSize[1], height = figSize[2], dpi = 600,
         filename = file.path(dir,"Figures","PlotProxyAgeResPlus.png"))
}
```


###Plot a histagram based on record length over the Holocene
```{r}
plotRange <- ggplot(proxyDf)+
  geom_vline(xintercept=median(proxyDf$ageRange), size=0.8) +
  geom_vline(xintercept=mean(proxyDf$ageRange), size=0.8, linetype=2) +
  geom_histogram(aes(ageRange,fill=CategorySpec), color='Black', alpha=0.7, breaks = seq(0,max(proxyDf$ageRange,na.rm=TRUE)+500,500)) +
  scale_fill_manual(values=plotSettings$color) +
  scale_x_continuous(name = "Record Length (binwidth = 300 years)",
                     limits=c(2900,12000),expand=c(0,0),breaks=seq(3000,12000,2000)) +
  scale_y_continuous(name="Count of Records", oob=scales::squish, limits=c(0,350), expand=c(0,0))+
  coord_flip()+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'White',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank(),legend.position = c(0.5,0.6))#legend.position = 'none')# legend.position = c(0.5,0.7))

plotRange
if (save) {
  ggsave(plot=plotRange, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dir,"Figures","PlotProxyAgeRange.png"))
}
```

###Plot a figure showiang temporal variability over the Holocene (using geochronR)
```{r}
plotTimeData <- plotTimeAvailabilityTs(lipdTSO,age.range = c(0,12000),step=100,group='CategorySpecific')
plotTime <- ggplot(plotTimeData$data,aes(yvec,value))+
  geom_area(alpha=0.7,aes(fill=group),color='Black',size=0.2)+
  scale_fill_manual(values=plotSettings$color) +
  scale_x_reverse(name = "Age (yr BP)", limits=c(12000,0),expand=c(0,0),n.breaks=7)+
  scale_y_continuous(name = "Count of Records",limits=c(0,length(lipdTSO)),expand=c(0,0),
                     labels=seq(0,length(lipdTSO),100), breaks=seq(0,length(lipdTSO),100))+
  theme_bw()+
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'White',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.key.height = unit(0.1, "in"),
        legend.key.width = unit(0.1, "in"),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))

plotTime
if (save) {
  ggsave(plot=plotTime, width = figSize[1], height = figSize[2], units='in', dpi = 600,
         filename = file.path(dir,"Figures","PlotTimeAvailability.png"))
}
```


```{r}
#Plot Figure 2 count by regions

pointData <- data.frame(longitude=c(proxyDf$longitude),latitude=c(proxyDf$latitude))
pointData <- spTransform(SpatialPointsDataFrame(coords=pointData,data = pointData, proj4string = CRS(PROJorig)),CRSobj = PROJ)
proxyDf$lonsPrj <- pointData@coords[,1]
proxyDf$latsPrj <- pointData@coords[,2]


regionsSelect$all       <- refregions
regionsSelect$select    <- subset(refregions, Acronym %in% proxyDf$ipccReg)
regionsSelect$composite <- subset(refregions, Acronym %in% colnames(read.csv(file.path(dir,'Data','RegionComposites','T','MedianTSbyRegion.csv'))))

dataTable <- fortify(regionsSelect$select)
dataTable$Count     <- NA
dataTable$CountName <- NA
dataTable$Region    <- NA

#Set Breaks and color scheme with lowest group as grey
figBreaks <- c(5,10,15,20,30,50,80)
figlabels <- c(paste("<",figBreaks[1]+1),
               paste(as.character(figBreaks[-length(figBreaks)]+1),"-",
                     as.character(figBreaks[-1])),
               paste(">",figBreaks[length(figBreaks)]))
figPalette <- c("#CCCCCC",RColorBrewer::brewer.pal(n=7, name = "YlOrRd"))

for (reg in list(levels(regionsSelect$select@data[["Acronym"]]))[[1]]){
  i = which(refregions@data[["Acronym"]]==reg)
  count <- length(which(proxyDf$region==reg))
  if (count == 0){         countName <- NA
  } else if (count <= figBreaks[1]){ countName <- 0
  } else if (count <= figBreaks[2]){ countName <- 1
  } else if (count <= figBreaks[3]){ countName <- 2
  } else if (count <= figBreaks[4]){ countName <- 3
  } else if (count <= figBreaks[5]){ countName <- 4
  } else if (count <= figBreaks[6]){ countName <- 5
  } else if (count <= figBreaks[7]){ countName <- 6
  } else {countName <- 7}
  dataTable$Count[which(dataTable$id==reg)]     <- count
  dataTable$CountName[which(dataTable$id==reg)] <- countName
  dataTable$Region[which(dataTable$id==reg)]    <-reg
  print(reg)
  print(count)
}

#Plot
proxyMapRegions <- basemap + 
  #Add refrence regions boundaries
  geom_map(data=regionsSelect$select, map=dataTable, alpha=0.75, size=0.5, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id,fill=as.factor(dataTable$CountName))) +
  scale_fill_manual(values=figPalette,labels=figlabels)+
  #Add proxy sites
  geom_point(data=as.data.frame(proxyDf), aes(x=lonsPrj , y=latsPrj), shape=1,size=0.8) +
  #Format Legend
  theme(plot.background = element_rect(fill = 'white',color='white'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.position = c(0.5,-0.01),
        legend.direction = "horizontal",
        legend.title=element_blank(),
        legend.background=element_rect(colour='black',size=0.4),
        legend.margin=margin(t = 1, r = 1, b = 3, l = -4.5, unit = "pt"),
        legend.key.width  = (unit(35, 'pt')),
        legend.key.height = (unit(5, 'pt')),
        legend.text = element_text(family='sans',size=8))

proxyMapRegions


if (save) {
  ggsave(plot=proxyMapRegions, width = 6, height = (6/1.97+0.5), dpi = 600,
       filename = file.path(dir,"Figures",paste('PlotCountByRegion_',var,'.png',sep='')))
}


#Plot Figure 2 count by regions



#Set Breaks and color scheme with lowest group as grey

#Plot



```

#Map proxy data with IPCC regions
```{r}
#Plot Figure 1 proxy type for each site
proxyMapSites <- basemap +
  geom_map(data=regionsSelect$select, map=dataTable, alpha=0.75, size=0.3, color='black' , 
           aes(x=long, y=lat, group=group, map_id=id),fill=NA,linetype = "dashed") + 
  geom_star(data= as.data.frame(proxyDf),aes(x=lonsPrj , y=latsPrj,
                                                  starshape=CategorySpec, fill=CategorySpec),
            size=1.5,color='Black',alpha=1,starstroke=0.3) + 
  scale_fill_manual(values=plotSettings$color,name= 'Proxy Category') +
  scale_starshape_manual(values=plotSettings$shape,name= 'Proxy Category') +
  theme(text = element_text(family=figFont,size=figText),
        plot.background = element_rect(fill = 'white',color='Black'),
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "in"),
        legend.background =  element_rect(fill = alpha('white', 0.85),size=0.5),#alpha=0.5),
        legend.margin = margin(c(0, 0.1, 0.05, 0.06), unit="in"),
        legend.key.height = unit(0.12, "in"),
        legend.key.width = unit(0.12, "in"),
        legend.position = c(0.15,0.28),
        legend.title = element_blank())#,legend.position = 'none')# legend.position = c(0.5,0.7))

proxyMapSites
if (save) {
  ggsave(plot=proxyMapSites, width = 6, height = 3.5, dpi = 600,
       filename = file.path(dir,"Figures",paste('PlotProxyTypeRegion_',var,'.png',sep='')))
}
```
```{r}
map <- ggarrange(proxyMapSites+theme(legend.position = c(0.05,0.3)), 
                 plotTime+theme(legend.position = 'none'),
                 ncol=1,widths=c(6),heights=c(3.5,1.5))
map
if (save) {
  ggsave(plot=map, width = 6.5, height = 5, dpi = 600,
       filename = file.path(dir,"Figures",paste('PlotProxyTypeRegion_',var,'_withTime.png',sep='')))
}
```








